'use client';
import {useEffect,useRef,useState} from 'react';
import {supabase} from '@/lib/supabase/browser';
import {useDialog} from '@/contexts/DialogContext';
import ServiceTerms,{emptyServiceTerms,validateServiceTerms} from '../subcontractors/ServiceTerms';
import {personnelInput as input,personnelButton as button,personnelSecondary as secondary} from '@/lib/personnel/workspace';
const blank={name:'',category:'',price:'',billing_unit:'event',...emptyServiceTerms};
export default function PersonnelServices({personId,canManage}:{personId:string;canManage:boolean}){
 const [rows,setRows]=useState<any[]>([]),[form,setForm]=useState({...blank}),[editing,setEditing]=useState<string|null>(null),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const lock=useRef(false);const {showConfirm}=useDialog();
 async function load(){setLoading(true);const {data,error}=await supabase.from('personnel_services').select('*').eq('person_id',personId).order('category').order('name');if(error)setError(error.message);else setRows(data||[]);setLoading(false);}
 useEffect(()=>{void load();},[personId]);
 async function save(e:React.FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{
  if(!form.name.trim())throw new Error('Podaj nazwę usługi.');
  const price=form.price.trim()===''?null:Number(form.price.replace(',','.'));if(price!==null&&(!Number.isFinite(price)||price<0))throw new Error('Podaj nieujemną stawkę.');
  validateServiceTerms(form);
  const payload={...form,name:form.name.trim(),category:form.category.trim(),price,person_id:personId};
  const result=editing?await supabase.from('personnel_services').update(payload).eq('id',editing).eq('person_id',personId).select('id').single():await supabase.from('personnel_services').insert(payload).select('id').single();
  if(result.error)throw result.error;setVisible(false);await load();
 }catch(e:any){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 async function remove(id:string){if(lock.current)return;lock.current=true;try{if(!await showConfirm({title:'Usuń usługę',message:'Usunąć usługę z katalogu współpracownika?',confirmText:'Usuń',cancelText:'Anuluj'}))return;setBusy(true);const {error}=await supabase.from('personnel_services').delete().eq('id',id).eq('person_id',personId).select('id').single();if(error)throw error;await load();}catch(e:any){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 return <section className="space-y-4 rounded-xl bg-white/[0.035] p-5"><header className="flex justify-between gap-3"><h2 className="text-lg uppercase">Usługi współpracownika</h2>{canManage&&<button className={button} disabled={busy} onClick={()=>{setEditing(null);setForm({...blank});setVisible(true);setError('');}}>Dodaj usługę</button>}</header>
 <p className="text-sm opacity-60">Stawki umowne brutto w PLN. Katalog nie zmienia kwot w zapisanych umowach.</p>
 {error&&<p role="alert" className="text-red-300">{error}</p>}
 {visible&&<form onSubmit={save} className="space-y-3"><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2">{([['name','Nazwa usługi *'],['category','Kategoria'],['price','Stawka brutto (zł)']] as const).map(([key,label])=><label key={key}>{label}<input className={input} required={key==='name'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Sposób rozliczenia<select className={input} value={form.billing_unit} onChange={e=>setForm({...form,billing_unit:e.target.value})}><option value="event">Za realizację</option><option value="hour">Za godzinę</option></select></label><div className="sm:col-span-2"><ServiceTerms value={form} onChange={v=>setForm({...form,...v})} rateHint="Przedłużenie i dojazd: stawki umowne brutto. Zasady rozliczania kilometrów wpisz w warunkach."/></div></fieldset><div className="flex gap-2"><button disabled={busy} className={button}>{busy?'Zapisywanie…':'Zapisz usługę'}</button><button type="button" disabled={busy} className={secondary} onClick={()=>setVisible(false)}>Anuluj</button></div></form>}
 {loading?<p>Ładowanie usług…</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Usługa / kategoria','Stawka brutto','Czas w cenie','Przedłużenie','Dojazd','Warunki',''].map((h,i)=><th key={i} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-white/5"><td className="p-3">{row.name}<div className="text-xs opacity-60">{row.category}</div></td><td className="p-3">{row.price==null?'Do ustalenia':`${Number(row.price).toLocaleString('pl-PL')} zł / ${row.billing_unit==='hour'?'h':'realizację'}`}</td><td className="p-3">{row.included_hours==null?'—':`${row.included_hours} h`}</td><td className="p-3">{row.overtime_hourly_rate==null?'—':`${row.overtime_hourly_rate} zł/h`}</td><td className="p-3">{row.travel_rate_per_km==null?'—':`${row.travel_rate_per_km} zł/km`}</td><td className="p-3 whitespace-pre-wrap">{row.performance_requirements||'—'}</td><td className="p-3">{canManage&&<div className="flex gap-2"><button disabled={busy} className={secondary} onClick={()=>{setEditing(row.id);setForm({name:row.name,category:row.category,price:row.price==null?'':String(row.price),billing_unit:row.billing_unit,included_hours:row.included_hours,overtime_hourly_rate:row.overtime_hourly_rate,travel_rate_per_km:row.travel_rate_per_km,performance_requirements:row.performance_requirements});setVisible(true);setError('');}}>Edytuj</button><button disabled={busy} className="text-red-300" onClick={()=>void remove(row.id)}>Usuń</button></div>}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-4 opacity-60">Brak usług. Dodaj pierwszą usługę i jej warunki.</p>}</div>}
 </section>;
}
