'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {supabase} from '@/lib/supabase/browser';
import SearchCombobox,{type SearchComboboxOption} from '@/components/crm/SearchCombobox';
import {useSnackbar} from '@/contexts/SnackbarContext';
const input='mt-1 w-full rounded-lg border border-white/10 bg-[#250914] px-3 py-2';
export default function EventPartnerArrangement({eventId,canManage,children}:{eventId:string;canManage:boolean;children:ReactNode}){
 const [form,setForm]=useState({enabled:false,partner:'',notes:'',order_reference:'',include_contract:false});
 const [options,setOptions]=useState<SearchComboboxOption[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 const [expanded,setExpanded]=useState(false);
 const lock=useRef(false);const {showSnackbar}=useSnackbar();
 useEffect(()=>{let live=true;setLoading(true);setLoaded(false);setError('');
 async function load(){try{
 const [saved,orgs,contacts,event]=await Promise.all([
 supabase.from('event_partner_arrangements').select('*').eq('event_id',eventId).maybeSingle(),
 supabase.from('organizations').select('id,name,alias').order('name'),
 supabase.from('contacts').select('id,full_name,first_name,last_name,email,phone').order('last_name'),
 supabase.from('events').select('organization_id,contact_person_id').eq('id',eventId).single()]);
 for(const r of [saved,orgs,contacts,event])if(r.error)throw r.error;
 if(!live)return;
 setOptions([...(orgs.data||[]).map(o=>({id:`org:${o.id}`,label:o.alias?`${o.name} (${o.alias})`:o.name,description:'Organizacja / hotel'})),...(contacts.data||[]).map(c=>({id:`contact:${c.id}`,label:c.full_name||[c.first_name,c.last_name].filter(Boolean).join(' ')||c.email||'Kontakt',description:c.email,keywords:c.phone}))]);
 const data=saved.data;const organization=data?data.organization_id:event.data?.organization_id;const contact=data?data.contact_id:event.data?.contact_person_id;
 setForm({enabled:data?.enabled||false,partner:organization?`org:${organization}`:contact?`contact:${contact}`:'',notes:data?.notes||'',order_reference:data?.order_reference||'',include_contract:data?.include_contract||false});setLoaded(true);
 }catch(e:any){if(live)setError(e.message||'Nie udało się pobrać ustaleń.');}finally{if(live)setLoading(false);}}
 void load();return()=>{live=false;};},[eventId]);
 async function save(){if(lock.current||!loaded||!canManage)return;setError('');if(form.enabled&&!form.partner){setError('Wybierz partnera biznesowego.');return;}if(form.enabled&&!form.notes.trim()){setError('Opisz ustalenia z partnerem.');return;}lock.current=true;setBusy(true);
 try{const [kind,id]=form.partner.split(':');const {data,error}=await supabase.from('event_partner_arrangements').upsert({event_id:eventId,enabled:form.enabled,organization_id:kind==='org'?id:null,contact_id:kind==='contact'?id:null,notes:form.notes.trim(),order_reference:form.order_reference.trim(),include_contract:form.include_contract},{onConflict:'event_id'}).select('order_reference,include_contract').single();if(error)throw error;setForm(current=>({...current,order_reference:data.order_reference,include_contract:data.include_contract}));setExpanded(false);showSnackbar('Zapisano ustalenia współpracy partnerskiej.','success');}catch(e:any){setError(e.message||'Nie udało się zapisać ustaleń.');}finally{lock.current=false;setBusy(false);}}
 return <><section className="no-print mb-4 space-y-2 rounded-xl bg-[#381020] px-4 py-3 text-[#e5e4e2]"><h2 className="text-sm uppercase">Współpraca partnerska</h2>{loading?<p>Ładowanie ustaleń…</p>:<fieldset disabled={!canManage||busy||!loaded} className="space-y-4"><div className="flex flex-wrap items-center gap-3"><button type="button" role="switch" aria-checked={form.enabled} aria-label="Współpraca partnerska" onClick={()=>{setForm({...form,enabled:!form.enabled});setExpanded(true);}} className={`relative h-6 w-11 rounded-full transition-colors ${form.enabled?'bg-[#d3bb73]':'bg-white/15'}`}><span className={`absolute left-0.5 top-0.5 h-5 w-5 rounded-full bg-white transition-transform ${form.enabled?'translate-x-5':''}`}/></button><span className="text-sm">Realizacja na podstawie ustaleń z partnerem</span><button type="button" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded} className="ml-auto text-xs text-[#d3bb73]">{expanded?'Zwiń szczegóły ▴':'Szczegóły ▾'}</button></div>{form.enabled&&<><p className="text-sm text-[#d3bb73]">{form.order_reference?`Numer zamówienia: ${form.order_reference}`:'Numer zamówienia zostanie nadany przy zapisie ustaleń.'}</p><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.include_contract} onChange={e=>{setForm({...form,include_contract:e.target.checked});setExpanded(true);}} className="h-4 w-4 accent-[#d3bb73]"/>Dodaj umowę do współpracy</label></>}{expanded&&form.enabled&&<><p className="text-sm opacity-65">Zapisz partnera, zakres, uzgodnioną kwotę i termin płatności. Ustalenia są podstawą obsługi tego zamówienia w systemie. Osobną umowę możesz dodać opcjonalnie.</p><div><label className="mb-1 block text-sm">Partner biznesowy *</label><SearchCombobox value={form.partner} options={options} disabled={!canManage||busy} onChange={partner=>setForm({...form,partner})} ariaLabel="Partner biznesowy" placeholder="Wyszukaj hotel, firmę lub kontakt…"/></div><label className="block text-sm">Ustalenia z partnerem *<textarea className={input} rows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Kto i kiedy potwierdził zlecenie, zakres, uzgodniona kwota, termin płatności…"/></label><label className="block text-sm">Numer zamówienia<input className={input} value={form.order_reference} readOnly placeholder="Nadawany automatycznie przy zapisie"/></label></>}{canManage&&expanded&&<button type="button" disabled={busy||!loaded} onClick={()=>void save()} className="rounded-lg bg-[#d3bb73] px-4 py-2 text-[#250914] disabled:opacity-50">{busy?'Zapisywanie…':'Zapisz ustalenia'}</button>}</fieldset>}{error&&<p role="alert" className="text-red-300">{error}</p>}</section>{loaded&&!loading&&(!form.enabled||form.include_contract)&&children}</>;
}
