"use client";
import ProductPackageResourcesEditor from './ProductPackageResourcesEditor';
import ProductPackageCostsEditor from './ProductPackageCostsEditor';
import type { ProductSalesPackage } from '@/lib/CRM/Offers/productSalesPackages';
export default function ProductPackagePicker({options,selectedId,onSelect,onChange,disabled,discountPercent=0}:{options:ProductSalesPackage[];selectedId:string;onSelect:(id:string)=>void;onChange:(options:ProductSalesPackage[])=>void;disabled?:boolean;discountPercent?:number}) {
 if(!options.length)return null;
 const selected = options.find(p => p.id === selectedId);
 return <section className="space-y-3 rounded-xl bg-[#d3bb73]/5 p-4"><h3 className="text-sm font-medium text-[#e5e4e2]">Wybierz pakiet do kalkulacji</h3><p className="text-xs text-[#e5e4e2]/55">Cena pakietu obejmuje jego zakres. Dodatki produktu nie są naliczane automatycznie. Skład pakietu nie zmienia istniejących rezerwacji sprzętu.</p><div className="grid gap-2 sm:grid-cols-3">{options.map(p=><button key={p.id} type="button" disabled={disabled} aria-pressed={selectedId===p.id} onClick={()=>onSelect(p.id)} className={`rounded-lg p-3 text-left ${selectedId===p.id?'bg-[#d3bb73]/15':'bg-black/15'}`}><span className="block text-sm text-[#e5e4e2]">{p.name}</span><span className="mt-1 block text-xs text-[#e5e4e2]/55">{p.included_label}</span><span className="mt-2 block text-sm text-[#d3bb73]">{p.price_net.toLocaleString('pl-PL')} zł netto</span></button>)}</div><button type="button" disabled={disabled} onClick={()=>onSelect('')} className="text-xs text-[#d3bb73]">Wycena pojedynczych elementów zamiast pakietu</button>{selectedId&&<details><summary className="cursor-pointer text-xs text-[#d3bb73]">Dostosuj ceny i zakres pakietów tylko w tej ofercie</summary><div className="mt-3 space-y-3">{options.map(p=><div key={p.id} className="grid gap-2 rounded-lg bg-black/10 p-3 sm:grid-cols-2"><label className="text-xs text-white/60">{p.name} — netto<input type="number" min="0" step="0.01" disabled={disabled} value={Number.isFinite(p.price_net)?p.price_net:''} onChange={e=>onChange(options.map(o=>o.id===p.id?{...o,price_net:e.target.valueAsNumber}:o))} className="mt-1 w-full rounded bg-black/15 p-2 text-sm text-white"/></label><label className="text-xs text-white/60">Zakres<input disabled={disabled} maxLength={95} value={p.included_label} onChange={e=>onChange(options.map(o=>o.id===p.id?{...o,included_label:e.target.value}:o))} className="mt-1 w-full rounded bg-black/15 p-2 text-sm text-white"/></label></div>)}</div></details>}{selected && <div className="space-y-2"><ProductPackageResourcesEditor value={selected} disabled={disabled} onChange={resources => onChange(options.map(p => p.id === selected.id ? { ...p, resources } : p))}/>{!selected.resources && <p className="text-xs text-[#d3bb73]">Uzupełnij sprzęt i obsadę przed rezerwacją zasobów tego pakietu.</p>}<ProductPackageCostsEditor value={selected} disabled={disabled} salePriceNet={selected.price_net * (1 - discountPercent / 100)} onChange={cost_items => onChange(options.map(p => p.id === selected.id ? { ...p, cost_items } : p))}/><p className="text-xs text-[#e5e4e2]/45">Koszty dotyczą wybranego pakietu tylko w tej ofercie. Marża uwzględnia rabat pozycji, przed rabatem całej oferty. Zmiany katalogu nie nadpiszą tej kalkulacji.</p></div>}</section>;
}
