/*
  # Sample Data for Conferences Page

  Adds professional content for all sections of the conferences page
*/

-- Hero section
INSERT INTO conferences_hero (title, subtitle, cta_primary, cta_secondary, trust_badge) VALUES
('Kompleksowa obsługa techniczna konferencji', 'Profesjonalne nagłośnienie, multimedia i realizacja live. Od małych spotkań po konferencje dla 500+ uczestników.', 'Wyceń swoją konferencję', 'Sprawdź dostępność', 'Obsługujemy wydarzenia w północnej i centralnej Polsce')
ON CONFLICT DO NOTHING;

-- Problems and solutions
INSERT INTO conferences_problems (title, problem_description, solution_description, icon_name, display_order) VALUES
('Niesłyszalni prelegenci', 'Głośniki salowe nie wystarczają, uczestnicy w tylnych rzędach nie słyszą prelegentów. Bezprzewodowe mikrofony szwankują.', 'Profesjonalny system nagłośnienia dopasowany do akustyki sali. Bezprzewodowe mikrofony Sennheiser/Shure ze zdublowanymi odbiornikami. Operator audio na miejscu.', 'Mic', 1),
('Problemy z prezentacjami', 'Prelegenci nie wiedzą jak podłączyć laptop, prezentacje nie działają, czcionki nieczytelne na ekranie.', 'Dedykowany operator prezentacji, rezerwowy laptop, bezprzewodowe clickery premium, system playoutu z przełączaniem źródeł. Wsparcie techniczne on-site.', 'Presentation', 2),
('Ciemna scena i zła widoczność', 'Domowe oświetlenie nie wystarcza. Prelegenci są niewidoczni, slajdy nieczytelne.', 'Profesjonalne oświetlenie sceniczne LED + reflektory follow spot. Oświetlenie prelegentów, ekranów i sal. Operator światła na miejscu.', 'Lightbulb', 3),
('Brak transmisji online', 'Część gości nie może uczestniczyć stacjonarnie. Firma potrzebuje transmisji na żywo i nagrania eventu.', 'Realizacja streamingu LIVE wielokamerowego. Platforma: YouTube, Zoom, własna. Montaż materiału video post-produkcja.', 'Video', 4),
('Chaos techniczny i koordynacja', 'Brak osoby odpowiedzialnej za technikę. Awarie w trakcie eventu. Nikt nie wie kto za co odpowiada.', 'Kierownik techniczny MAVINCI koordynuje całość. Rezerwowy sprzęt, backup zasilania. Scenariusz techniczny i próby przed eventem.', 'Shield', 5),
('Nieodpowiednia sala i logistyka', 'Sala nie ma odpowiedniego nagłośnienia, ekranów, zaciemnień. Trzeba wszystko dowieźć i zamontować.', 'Audyt sali, doradztwo techniczne, kompleksowa logistyka. Dostarczamy i montujemy cały sprzęt. Demontaż po evencie.', 'Truck', 6);

-- Technical services
INSERT INTO conferences_services (category_name, category_description, services_list, icon_name, display_order) VALUES
('Audio i nagłośnienie', 'Profesjonalne systemy dźwiękowe dostosowane do wielkości i akustyki sali', ARRAY['Mikrofony bezprzewodowe (nagłówne, doręczne, krawatowe)', 'Pulpity i miksery audio cyfrowe', 'Systemy nagłośnienia line array i punktowe', 'Monitory estradowe i odsłuchy', 'Operator dźwięku i realizator audio', 'Nagranie ścieżki audio eventu'], 'Volume2', 1),
('Wideo i obraz', 'Wielokamerowa realizacja live, projektory i ekrany LED', ARRAY['Kamery 4K z operatorami', 'Realizacja wielokamerowa live', 'Projektory Full HD / 4K od 5000 do 20000 ANSI', 'Ekrany projekcyjne fast-fold i elektryczne', 'Ściany LED modułowe', 'Reżyserka wideo i mixer wizji'], 'Camera', 2),
('Oświetlenie sceniczne', 'Profesjonalne reflektory LED, oświetlenie dekoracyjne i techniczne', ARRAY['Reflektory LED PAR i wash', 'OświetlenieFollow Spot', 'Oświetlenie dekoracyjne i ambientowe', 'Pulpity DMX i operatorzy światła', 'Oświetlenie sali i publiczności', 'Scenografia świetlna i mapping'], 'Lightbulb', 3),
('Prezentacje i multimedia', 'Playout prezentacji, przełączanie źródeł, grafika live', ARRAY['Operator prezentacji on-site', 'System playoutu i przełączania źródeł', 'Bezprzewodowe clickery premium', 'Laptop rezerwowy', 'Konwertery sygnału (HDMI, SDI, VGA)', 'Grafika i niższe tytuły live'], 'Monitor', 4),
('Streaming i transmisje', 'Transmisje online na żywo, nagrania, post-produkcja', ARRAY['Streaming LIVE (YouTube, Vimeo, Zoom, platformy dedykowane)', 'Realizacja wielokamerowa online', 'Enkoder sprzętowy i software', 'Backup internetu (LTE/5G)', 'Nagranie materiału raw i zmontowanego', 'Post-produkcja i montaż video'], 'Wifi', 5),
('Logistyka i koordynacja', 'Kierownik techniczny, audyt sali, transport sprzętu', ARRAY['Kierownik techniczny MAVINCI', 'Audyt i wizja lokalna sali', 'Transport i montaż sprzętu', 'Próby techniczne przed eventem', 'Obsługa techniczna w trakcie', 'Demontaż i wywóz sprzętu'], 'Settings', 6);

-- Conference packages  
INSERT INTO conferences_packages (package_name, package_level, description, target_audience, features, price_info, display_order) VALUES
('BASIC', 'basic', 'Idealne dla małych konferencji, szkoleń i spotkań biznesowych', 'Do 50 uczestników, 1 sala, podstawowa obsługa', '{"audio": ["2 mikrofony bezprzewodowe", "Nagłośnienie podstawowe", "Operator audio"], "video": ["Projektor Full HD", "Ekran 3x2m", "Laptop do prezentacji"], "light": ["Oświetlenie sali", "Oświetlenie sceny podstawowe"], "other": ["Operator techniczny", "Wsparcie on-site"]}', 'od 2500 zł netto', 1),
('STANDARD', 'standard', 'Kompleksowa obsługa konferencji średniej wielkości', 'Od 50 do 150 uczestników, pełna realizacja AV', '{"audio": ["4-6 mikrofonów bezprzewodowych", "System nagłośnienia line array", "Mikser cyfrowy", "Nagranie audio"], "video": ["2 kamery Full HD", "Realizacja live", "Projektor 8000 ANSI lub ekran LED", "Operator prezentacji"], "light": ["Oświetlenie sceniczne LED", "Follow spot", "Operator światła"], "stream": ["Możliwość streamingu LIVE", "Nagranie video"], "other": ["Kierownik techniczny", "2-3 operatorów", "Backup sprzętu"]}', 'od 8000 zł netto', 2),
('PRO', 'pro', 'Premium dla dużych konferencji i wydarzeń korporacyjnych', 'Powyżej 150 uczestników, wielokamerowo, streaming', '{"audio": ["Nielimitowane mikrofony", "System nagłośnienia premium", "Pulpit cyfrowy Yamaha/Allen&Heath", "Monitory estradowe", "Nagranie wielośladowe"], "video": ["3-5 kamer 4K", "Realizacja live wielokamerowa", "Ekrany LED modułowe lub projektory 12K+", "Reżyserka i mixer wizji"], "light": ["Pełne oświetlenie sceniczne", "Moving heads", "Oświetlenie dekoracyjne", "Mapping i efekty"], "stream": ["Streaming 4K multi-camera", "Platforma dedykowana", "Backup internetu"], "multimedia": ["System playoutu", "Grafika live", "Niższe tytuły"], "other": ["Pełen zespół techniczny", "Kierownik + 4-6 operatorów", "Rezerwowy sprzęt", "Próby dzień wcześniej"]}', 'od 20000 zł netto', 3);

-- Case studies
INSERT INTO conferences_case_studies (project_name, client_name, event_type, challenge, solution, result, equipment_used, attendees_count, display_order) VALUES
('Konferencja Liderów Biznesu 2024', 'Confidential', 'Konferencja korporacyjna', 'Dwudniowa konferencja dla 300 uczestników z transmisjami online na 3 platformach jednocześnie. Wymagana pełna realizacja wielokamerowa + streaming bez przerw technicznych.', 'Realizacja 4-kamerowa z reżyserką live, streaming równoległy na YouTube, Zoom i platformę firmową. System nagłośnienia L-Acoustics, 8 mikrofonów bezprzewodowych, ekrany LED 6x3m. Kierownik techniczny + 6 operatorów.', 'Event przebiegł bez żadnych problemów technicznych. Streaming obejrzało łącznie 1200 osób online. Klient otrzymał zmontowany materiał video w 48h po evencie.', ARRAY['Kamery Sony 4K (4 szt)', 'System nagłośnienia L-Acoustics', 'Ekrany LED 6x3m', 'Mikrofony Sennheiser (8 szt)', 'Enkoder StreamLabs', 'Oświetlenie LED PAR64 (24 szt)', 'Pulpit Yamaha QL5'], 300, 1),
('Międzynarodowe Forum Medyczne', 'Organizacja Non-profit', 'Konferencja medyczna, 2 sale równolegle', 'Obsługa 2 sal konferencyjnych jednocześnie z tłumaczeniem symultanicznym i transmisją między salami. Prelegenci międzynarodowi, zero tolerancji na błędy.', 'Dwie niezależne realizacje audio-video, system tłumaczeń symultanicznych, transmisja wizji między salami. 12 mikrofonów, 2 ekrany LED, oświetlenie sceniczne w obu salach. 8-osobowy zespół techniczny.', 'Konferencja oceniona jako wzorcowa pod względem technicznym. Tłumaczenie działało bez zarzutu, prelegenci wyrazili uznanie za profesjonalizm obsługi.', ARRAY['Mikrofony Shure (12 szt)', 'System tłumaczeń Bosch', 'Projektory 10K ANSI (2 szt)', 'Kamery PTZ (4 szt)', 'Oświetlenie Follow Spot', 'Pulpity audio Yamaha (2 szt)'], 450, 2),
('Szczyt Startupów Tech', 'Fundacja Rozwoju Innowacji', 'Konferencja technologiczna z pitchami', 'Dynamiczny event z 20 prezentacjami startupów po 5 minut każda. Wymagana szybka zmiana prelegentów, grafika live z logotypami, timer na scenie.', 'System playoutu prezentacji z operatorem, grafika live z CG, timer LED na scenie widoczny dla prelegentów. Bezprzewodowe clickery premium, laptop backup. 3-kamerowa realizacja + streaming.', 'Event uznany za najlepiej zorganizowany w historii fundacji. Żadna prezentacja nie miała problemów technicznych. Nagranie video wykorzystane w kampanii marketingowej.', ARRAY['Kamery Blackmagic (3 szt)', 'System CG Graphics', 'Timer LED DMX', 'Mikrofony nagłówne (5 szt)', 'Ekran LED 8x4m', 'Clickery Logitech', 'System playoutu ProPresenter'], 200, 3);

-- Advantages
INSERT INTO conferences_advantages (title, description, icon_name, display_order) VALUES
('Doświadczenie w eventach korporacyjnych', 'Ponad 150 zrealizowanych konferencji rocznie. Znamy specyfikę eventów biznesowych, potrafimy obsłużyć wymagających klientów i międzynarodowych prelegentów.', 'Award', 1),
('Sprzęt premium i backup', 'Pracujemy wyłącznie na sprzęcie marek Sennheiser, Shure, L-Acoustics, Sony, Blackmagic. Zawsze mamy sprzęt rezerwowy i plan B na każdy scenariusz.', 'Shield', 2),
('Pełen zespół operatorów', 'Nie wynajmujemy sprzętu bez obsługi. Każdy event ma dedykowanego kierownika technicznego i zespół operatorów audio, video, światła.', 'Users', 3),
('Realizacja live i streaming', 'Specjalizujemy się w transmisjach wielokamerowych na żywo. Obsługujemy YouTube, Zoom, Teams, Vimeo oraz platformy dedykowane.', 'Video', 4),
('Audyt i doradztwo techniczne', 'Przed każdym eventem robimy wizję lokalną sali. Doradzamy w wyborze optymalnej konfiguracji sprzętowej. Proponujemy rozwiązania oszczędzające budżet.', 'FileSearch', 5),
('Obsługa północnej i centralnej Polski', 'Główne biuro w Bydgoszczy, magazyn sprzętu. Obsługujemy Warszawę, Gdańsk, Poznań, Toruń, Bydgoszcz i okolice. Dojazd w 24h.', 'MapPin', 6);

-- Process steps
INSERT INTO conferences_process (step_number, step_title, step_description, duration_info, icon_name, display_order) VALUES
(1, 'Konsultacja i brief', 'Rozmowa o evencie: liczba uczestników, agenda, specyfika sali, wymagania techniczne. Ustalamy zakres obsługi i wstępny harmonogram.', '30-60 minut, online lub stacjonarnie', 'MessageSquare', 1),
(2, 'Audyt sali i wizja lokalna', 'Jedziemy na miejsce, sprawdzamy salę, akustykę, oświetlenie, dostęp do prądu, logistykę. Wykonujemy pomiary i dokumentację fotograficzną.', '1-2 godziny, opcjonalnie', 'Search', 2),
(3, 'Propozycja techniczna i wycena', 'Przygotowujemy szczegółową konfigurację sprzętową, harmonogram montażu, składy zespołów operatorskich. Wycena z podziałem na pozycje.', '2-3 dni robocze', 'FileText', 3),
(4, 'Potwierdzenie i rezerwacja sprzętu', 'Po akceptacji oferty rezerwujemy sprzęt i zespół na dany termin. Ustalamy szczegóły logistyczne i scenariusz techniczny.', '1 dzień', 'CheckCircle', 4),
(5, 'Montaż i próby techniczne', 'Przyjazd na miejsce, montaż sprzętu, konfiguracja systemów, testy audio-video. Próby z prelegentami (jeśli wymagane).', 'Dzień przed eventem lub rano', 'Settings', 5),
(6, 'Realizacja eventu', 'Pełna obsługa techniczna w trakcie konferencji. Kierownik techniczny + operatorzy na stanowiskach. Reagujemy na bieżąco, rozwiązujemy problemy.', 'Czas trwania eventu + 1h', 'Play', 6),
(7, 'Demontaż i materiały video', 'Demontaż sprzętu, wywóz. Przygotowanie materiałów video (raw + montaż). Przekazanie nagrań w ciągu 48-72h.', '2-4 godziny demontaż, 2-5 dni video', 'Package', 7);

-- Pricing tiers
INSERT INTO conferences_pricing (tier_name, tier_description, price_range, attendees_range, whats_included, display_order) VALUES
('Mała konferencja / szkolenie', 'Podstawowa obsługa audio-video dla wydarzeń kameralnych', '2500 - 5000 zł netto', 'Do 50 osób', ARRAY['Nagłośnienie + 2 mikrofony', 'Projektor i ekran', 'Operator techniczny', 'Montaż i demontaż'], 1),
('Średnia konferencja', 'Pełna realizacja audio-video dla konferencji biznesowych', '8000 - 15000 zł netto', '50-150 osób', ARRAY['System nagłośnienia premium', '4-6 mikrofonów', 'Kamery i realizacja live', 'Ekran LED lub projektor 8K+', 'Oświetlenie sceniczne', 'Zespół 2-3 operatorów', 'Streaming (opcja)', 'Nagranie video'], 2),
('Duża konferencja premium', 'Kompleksowa obsługa eventów korporacyjnych i międzynarodowych', '20000 - 50000+ zł netto', 'Powyżej 150 osób', ARRAY['Pełen system audio line array', 'Nielimitowane mikrofony', 'Realizacja 3-5 kamer 4K', 'Ekrany LED modułowe', 'Oświetlenie sceniczne premium', 'Streaming wielokamerowy', 'Grafika live i CG', 'Pełen zespół + kierownik', 'Backup sprzętu', 'Próby dzień wcześniej', 'Post-produkcja video'], 3);

-- FAQ
INSERT INTO conferences_faq (question, answer, category, display_order) VALUES
('Ile kosztuje obsługa konferencji?', 'Ceny zaczynają się od 2500 zł netto dla małych szkoleń (do 50 osób, podstawowe nagłośnienie). Standardowa konferencja dla 100-150 osób to koszt 8000-15000 zł netto. Duże eventy premium powyżej 20000 zł netto. Finalna wycena zależy od zakresu technicznego, liczby mikrofonów, kamer, oświetlenia i czasu trwania.', 'pricing', 1),
('Czy robicie tylko wynajem sprzętu czy również obsługę?', 'Pracujemy wyłącznie w modelu „sprzęt + obsługa". Każdy event ma dedykowanego operatora lub pełen zespół techniczny. Nie wynajmujemy sprzętu bez naszych ludzi – to gwarancja jakości i braku problemów technicznych.', 'service', 2),
('Jak daleko dojeżdżacie?', 'Obsługujemy głównie północną i centralną Polskę: Warszawa, Bydgoszcz, Gdańsk, Poznań, Toruń oraz okolice. Dla dużych projektów jesteśmy w stanie dojechać dalej – najlepiej zapytać indywidualnie.', 'logistics', 3),
('Czy robicie streaming konferencji na żywo?', 'Tak, specjalizujemy się w transmisjach live. Obsługujemy YouTube, Vimeo, Zoom, Microsoft Teams oraz platformy dedykowane. Realizujemy streaming wielokamerowy w 4K z grafiką live i backupem internetu (LTE/5G).', 'streaming', 4),
('Co jeśli sala nie ma odpowiedniego nagłośnienia?', 'To nasza specjalność. Przywozimy cały sprzęt: nagłośnienie, mikrofony, projektory, ekrany, oświetlenie. Przed eventem robimy audyt sali i doradzamy optymalną konfigurację sprzętową.', 'technical', 5),
('Czy nagrywają Państwo konferencje?', 'Tak. Standardowo nagrywamy audio i video (jeśli w pakiecie są kamery). Nagranie raw przekazujemy w ciągu 48h. Opcjonalnie robimy montaż, korekty kolorystyczne, napisy i podsumowanie video – termin realizacji 5-7 dni.', 'video', 6),
('Ile czasu przed eventem trzeba Was zamówić?', 'Optymalnie 2-4 tygodnie przed terminem, żeby mieć pewność dostępności sprzętu i zespołu. Dla standardowych konferencji często jesteśmy w stanie zorganizować obsługę w tydzień. W nagłych przypadkach – dzwońcie, zawsze staramy się pomóc.', 'booking', 7),
('Czy macie sprzęt rezerwowy?', 'Tak. Na każdy większy event (powyżej pakietu BASIC) zabieramy sprzęt backup: rezerwowe mikrofony, kable, projektory zapasowe. Pracujemy na zasadzie podwójnego zabezpieczenia – jeśli coś się zepsuje, natychmiast podmieniamy.', 'technical', 8),
('Czy obsługujecie konferencje międzynarodowe?', 'Tak. Mamy doświadczenie w obsłudze eventów z prelegentami z całego świata. Obsługujemy systemy tłumaczeń symultanicznych, realizacje wielojęzyczne, grafiki live w językach obcych. Nasz zespół mówi po angielsku.', 'international', 9),
('Co jeśli prelegenci mają Maca i potrzebują adaptera?', 'Zawsze mamy wszystkie adaptery: USB-C, HDMI, VGA, DisplayPort, Thunderbolt. Do tego laptop rezerwowy z Windows i Mac. Operator prezentacji zadba o to, żeby każda prezentacja działała bez problemu.', 'technical', 10);
