-- Public SEO content corrections. Applied through the authenticated data API on 2026-09-29.

-- Replaying this migration preserves later CMS edits through old-value guards.

-- No schema, permissions, client records, inventory or CRM data are changed.

BEGIN;

UPDATE public.schema_org_global SET "organization_name" = 'MAVINCI Event & ART', "telephone" = '+48 698 212 279', "instagram_url" = NULL, "facebook_url" = 'https://www.facebook.com/Mavincieventart' WHERE id = '156f6b8e-0fde-4f72-968e-263adeb36e21' AND "organization_name" IS NOT DISTINCT FROM 'Mavinci Event & ART - Olsztyn' AND "telephone" IS NOT DISTINCT FROM '+48 698-212-279' AND "instagram_url" IS NOT DISTINCT FROM 'https://www.instagram.com/' AND "facebook_url" IS NOT DISTINCT FROM 'https://www.facebook.com/mavincieventart';

UPDATE public.schema_org_page_metadata SET "title" = 'Agencja eventowa Olsztyn – technika i eventy | MAVINCI', "description" = 'MAVINCI z Olsztyna: organizacja eventów i obsługa konferencji. Własna technika, nagłośnienie Meyer Sound, ekrany LED, streaming i integracje na Warmii i Mazurach.', "keywords" = ARRAY[]::text[] WHERE id = '72bc55f9-081e-4a9a-84e8-fa334c5d849f' AND "title" IS NOT DISTINCT FROM 'MAVINCI Event & ART | Profesjonalna Organizacja Wydarzeń' AND "description" IS NOT DISTINCT FROM 'Kompleksowa obsługa eventów firmowych: konferencje, integracje, gale, targi. Profesjonalne nagłośnienie, oświetlenie, streaming i kasyno eventowe.' AND "keywords" IS NOT DISTINCT FROM ARRAY['organizacja eventów','eventy firmowe','konferencje biznesowe','integracje firmowe','nagłośnienie imprez','oświetlenie sceniczne','kasyno na eventy']::text[];

UPDATE public.schema_org_page_metadata SET "title" = 'Obsługa konferencji Olsztyn – LED, streaming | MAVINCI', "description" = 'Obsługa techniczna konferencji w Olsztynie i na Warmii i Mazurach. Własne nagłośnienie Meyer Sound, ekrany LED, oświetlenie, multimedia i streaming.', "keywords" = ARRAY[]::text[] WHERE id = '34a2f141-d16c-4b76-9b30-36070c633e9a' AND "title" IS NOT DISTINCT FROM 'MAVINCI Event & ART | Techniczna Obsługa Konferencji | Ekran Led | Streaming' AND "description" IS NOT DISTINCT FROM 'Kompleksowa obsługa techniczna konferencji: nagłośnienie, projekcja, streaming, rejestracja wideo. Doświadczenie, profesjonalizm, nowoczesny sprzęt.' AND "keywords" IS NOT DISTINCT FROM ARRAY['obsługa konferencji','nagłośnienie konferencji','streaming konferencji','realizacja video','technika konferencyjna','eventy biznesowe','Ekran LED','Oświetlenie konferencyjne','multimedia konferencyjne','realizacja AV','realizacja kamerowa','ekrany LED konferencje','obsługa techniczna eventów','technika sceniczna konferencje','profesjonalne nagłośnienie','konferencje biznesowe olsztyn','konferencje biznesowe warszawa','konferencje biznesowe gdansk','obsługa wydarzeń','technika AV','operatorzy kamer','sprzęt konferencyjny']::text[];

UPDATE public.schema_org_page_metadata SET "title" = 'Streaming konferencji i eventów Olsztyn | MAVINCI', "description" = 'Streaming konferencji, wydarzeń firmowych i gal. MAVINCI Olsztyn: realizacja wielokamerowa, dźwięk, prezentacje i nagrania. Obsługujemy Warmię i Mazury.', "keywords" = ARRAY[]::text[] WHERE id = 'a0367212-7f38-40d5-bed0-b5ab706533fa' AND "title" IS NOT DISTINCT FROM 'Transmisje konferencji | nagrywanie | streaming| wideofilmowanie | Olsztyn |  Mavinci - Event & Art' AND "description" IS NOT DISTINCT FROM 'Profesjonalny streaming konferencji, eventów i wydarzeń hybrydowych. Realizacja multicam, dźwięk, grafiki, transmisja na zamknięte platformy lub social media. MAVINCI zapewnia stabilny obraz, realizację 4K i pełne zaplecze techniczne dla Twojego wydarzenia.' AND "keywords" IS NOT DISTINCT FROM ARRAY['transmisje na żywo','live studio','transmisje live','transmisje online','kamera streaming','livestream online','yt live','streaming na żywo','na żywo live','streamy na żywo','streaming konferencji','streaming eventów','realizacja streamingu','multicam streaming','realizacja transmisji','streaming 4K']::text[];

UPDATE public.schema_org_page_metadata SET "title" = 'Technika sceniczna i nagłośnienie Olsztyn | MAVINCI', "description" = 'Technika sceniczna w Olsztynie i na Warmii i Mazurach. Własny system Meyer Sound, ekrany LED, oświetlenie i realizatorzy na konferencje, gale i eventy.', "keywords" = ARRAY[]::text[] WHERE id = '9b921fa8-49ca-407c-b00e-f44d1ddbe6f7' AND "title" IS NOT DISTINCT FROM 'Technika Sceniczna dla Eventów | Sceny Mobilne, Oświetlenie, Nagłośnienie | MAVINCI' AND "description" IS NOT DISTINCT FROM 'Kompleksowa technika sceniczna: mobilne sceny, konstrukcje, oświetlenie, nagłośnienie i realizacja wydarzeń. Profesjonalne rozwiązania sceniczne dla koncertów, eventów firmowych i wydarzeń plenerowych.' AND "keywords" IS NOT DISTINCT FROM ARRAY['technika sceniczna','technika sceniczna olsztyn','technika sceniczna gdansk','technika sceniczna warszawa','technika sceniczna torun','konstrukcje sceniczne','oświetlenie sceniczne','nagłośnienie sceniczne','realizacja sceniczna','kratownice sceniczne','podesty sceniczne','obsługa techniczna eventów','stage tech','stage lighting','event production','technika estradowa']::text[];

UPDATE public.schema_org_page_metadata SET "title" = 'Integracje i eventy firmowe Olsztyn | MAVINCI', "description" = 'Integracje i eventy firmowe w Olsztynie i na Warmii i Mazurach. Scenariusz, teambuilding, wieczory tematyczne, muzyka i własne zaplecze techniczne MAVINCI.', "keywords" = ARRAY[]::text[] WHERE id = 'ccd8755b-f48f-4f86-877d-ecdcc662d9b6' AND "title" IS NOT DISTINCT FROM 'Integracje Firmowe | Eventy Teambuilding Gry i Aktywności dla Firm | MAVINCI' AND "description" IS NOT DISTINCT FROM 'Profesjonalne integracje firmowe dla zespołów — gry teambuilding, scenariusze eventowe, outdoor, indoor, aktywności wieczorne i kreatywne zadania. Wzmacniamy komunikację, motywację i relacje w firmie. Kompleksowa organizacja, technika, prowadzenie i multimedia.' AND "keywords" IS NOT DISTINCT FROM ARRAY['integracje firmowe','teambuilding','event firmowy','wyjazdy integracyjne','atrakcje na integrację','gry zespołowe dla firm','team building','scenariusze integracyjne','prowadzenie eventów','organizacja integracji,','integracja pracowników','animacje firmowe','gry wieczorne','aktywności outdoor','aktywności indoor','atrakcje eventowe','budowanie zespołu','team experience','eventy firmowe','integracja zespołu']::text[];

UPDATE public.schema_org_page_metadata SET "title" = 'Obsługa konferencji Olsztyn – technika i streaming | MAVINCI', "description" = 'Obsługa konferencji w Olsztynie: nagłośnienie Meyer Sound, ekrany LED, oświetlenie i streaming. MAVINCI — własna technika i zespół z Olsztyna.', "keywords" = ARRAY[]::text[] WHERE id = '5d63d10c-e11c-4089-b01e-e9e54820661b' AND "title" IS NOT DISTINCT FROM 'Techniczna Obsługa Konferencji | Ekran Led | Streaming | Kongresy|  MAVINCI Event & ART | Olsztyn' AND "description" IS NOT DISTINCT FROM 'Kompleksowa obsługa techniczna konferencji: nagłośnienie, projekcja, streaming, rejestracja wideo. Doświadczenie, profesjonalizm, nowoczesny sprzęt.' AND "keywords" IS NOT DISTINCT FROM ARRAY['multimedia konferencyjne Olsztyn','obsługa multimediów Olsztyn','obsługa prezentacji PowerPoint Olsztyn','obsługa prezentacji multimedialnych Olsztyn','operator prezentacji Olsztyn','operator PowerPoint Olsztyn','realizacja prezentacji konferencyjnych Olsztyn','technik multimediów Olsztyn','realizator multimediów Olsztyn','obsługa ekranów LED Olsztyn','obsługa telebimów Olsztyn','operator ekranów konferencyjnych Olsztyn','obsługa projektorów Olsztyn','obsługa projektorów multimedialnych Olsztyn','realizacja wizji konferencji Olsztyn','operator wizji Olsztyn','realizacja AV Olsztyn','obsługa AV konferencji Olsztyn','technika AV Olsztyn','multimedia na konferencję Olsztyn','multimedia na event Olsztyn','obsługa wystąpień prelegentów Olsztyn','realizacja konferencji Olsztyn','obsługa konferencji Olsztyn','wsparcie techniczne konferencji Olsztyn','obsługa slajdów konferencyjnych Olsztyn','obsługa keynote Olsztyn','obsługa prezentacji keynote Olsztyn','sterowanie multimediami Olsztyn','operator ekranu LED Olsztyn','obsługa transmisji prezentacji Olsztyn','obsługa wydarzeń biznesowych Olsztyn','wynajem projektorów Olsztyn','wynajem ekranów projekcyjnych Olsztyn','ekrany projekcyjne Olsztyn','ekrany LED konferencyjne Olsztyn','MAVINCI multimedia Olsztyn']::text[];

INSERT INTO public.polish_city_cases ("id", "city_key", "nominative", "genitive", "locative", "locative_preposition", "is_active") SELECT '0d67988e-a258-41e3-89bb-c4f8a315a070', 'ostroda', 'Ostróda', 'Ostródy', 'Ostródzie', 'w', true WHERE NOT EXISTS (SELECT 1 FROM public.polish_city_cases WHERE "city_key" IS NOT DISTINCT FROM 'ostroda');

INSERT INTO public.schema_org_places ("id", "business_id", "name", "locality", "postal_code", "region", "country", "display_order", "is_active", "is_global") SELECT '552dfbb5-7e2d-4dc5-afdb-64084df474d1', NULL, 'Ostróda', 'ostroda', '14-100', 'Województwo Warmińsko-Mazurskie', 'PL', 33, true, true WHERE NOT EXISTS (SELECT 1 FROM public.schema_org_places WHERE "locality" IS NOT DISTINCT FROM 'ostroda' AND "is_global" IS NOT DISTINCT FROM true);

INSERT INTO public.schema_org_page_metadata ("id", "page_slug", "title", "description", "keywords", "is_active", "schema_type", "priority", "change_frequency") SELECT '19cf06c3-a591-4c73-bc27-96a3d0e34375', 'oferta/konferencje/ostroda', 'Obsługa konferencji Ostróda – technika i streaming | MAVINCI', 'Obsługa konferencji w Ostródzie: nagłośnienie Meyer Sound, ekrany LED, oświetlenie i streaming. MAVINCI — własna technika i zespół z Olsztyna.', ARRAY[]::text[], true, 'Service', 0.8, 'monthly' WHERE NOT EXISTS (SELECT 1 FROM public.schema_org_page_metadata WHERE "page_slug" IS NOT DISTINCT FROM 'oferta/konferencje/ostroda');

INSERT INTO public.polish_city_cases ("id", "city_key", "nominative", "genitive", "locative", "locative_preposition", "is_active") SELECT '8341bef6-a412-460f-b938-06fd7bea895e', 'ilawa', 'Iława', 'Iławy', 'Iławie', 'w', true WHERE NOT EXISTS (SELECT 1 FROM public.polish_city_cases WHERE "city_key" IS NOT DISTINCT FROM 'ilawa');

INSERT INTO public.schema_org_places ("id", "business_id", "name", "locality", "postal_code", "region", "country", "display_order", "is_active", "is_global") SELECT '7b703801-70c9-4965-86b2-595b7f255986', NULL, 'Iława', 'ilawa', '14-200', 'Województwo Warmińsko-Mazurskie', 'PL', 34, true, true WHERE NOT EXISTS (SELECT 1 FROM public.schema_org_places WHERE "locality" IS NOT DISTINCT FROM 'ilawa' AND "is_global" IS NOT DISTINCT FROM true);

INSERT INTO public.schema_org_page_metadata ("id", "page_slug", "title", "description", "keywords", "is_active", "schema_type", "priority", "change_frequency") SELECT '88907a38-0e8f-42c3-b58e-a68f96faf3d1', 'oferta/konferencje/ilawa', 'Obsługa konferencji Iława – technika i streaming | MAVINCI', 'Obsługa konferencji w Iławie: nagłośnienie Meyer Sound, ekrany LED, oświetlenie i streaming. MAVINCI — własna technika i zespół z Olsztyna.', ARRAY[]::text[], true, 'Service', 0.8, 'monthly' WHERE NOT EXISTS (SELECT 1 FROM public.schema_org_page_metadata WHERE "page_slug" IS NOT DISTINCT FROM 'oferta/konferencje/ilawa');

INSERT INTO public.polish_city_cases ("id", "city_key", "nominative", "genitive", "locative", "locative_preposition", "is_active") SELECT 'c99195a5-f78f-4d33-9571-429a98a53001', 'gizycko', 'Giżycko', 'Giżycka', 'Giżycku', 'w', true WHERE NOT EXISTS (SELECT 1 FROM public.polish_city_cases WHERE "city_key" IS NOT DISTINCT FROM 'gizycko');

INSERT INTO public.schema_org_places ("id", "business_id", "name", "locality", "postal_code", "region", "country", "display_order", "is_active", "is_global") SELECT '4f4a1ab3-73bf-4b87-8b28-bc141ee84031', NULL, 'Giżycko', 'gizycko', '11-500', 'Województwo Warmińsko-Mazurskie', 'PL', 35, true, true WHERE NOT EXISTS (SELECT 1 FROM public.schema_org_places WHERE "locality" IS NOT DISTINCT FROM 'gizycko' AND "is_global" IS NOT DISTINCT FROM true);

INSERT INTO public.schema_org_page_metadata ("id", "page_slug", "title", "description", "keywords", "is_active", "schema_type", "priority", "change_frequency") SELECT 'e8866fc8-e9ed-43a2-991c-84c3f24d8253', 'oferta/konferencje/gizycko', 'Obsługa konferencji Giżycko – technika i streaming | MAVINCI', 'Obsługa konferencji w Giżycku: nagłośnienie Meyer Sound, ekrany LED, oświetlenie i streaming. MAVINCI — własna technika i zespół z Olsztyna.', ARRAY[]::text[], true, 'Service', 0.8, 'monthly' WHERE NOT EXISTS (SELECT 1 FROM public.schema_org_page_metadata WHERE "page_slug" IS NOT DISTINCT FROM 'oferta/konferencje/gizycko');

INSERT INTO public.polish_city_cases ("id", "city_key", "nominative", "genitive", "locative", "locative_preposition", "is_active") SELECT 'b53fb068-fb63-4fe4-bdf8-cad2f69ce19a', 'elk', 'Ełk', 'Ełku', 'Ełku', 'w', true WHERE NOT EXISTS (SELECT 1 FROM public.polish_city_cases WHERE "city_key" IS NOT DISTINCT FROM 'elk');

INSERT INTO public.schema_org_places ("id", "business_id", "name", "locality", "postal_code", "region", "country", "display_order", "is_active", "is_global") SELECT '60fd87e5-b6af-4a55-8765-faf933a7a13d', NULL, 'Ełk', 'elk', '19-300', 'Województwo Warmińsko-Mazurskie', 'PL', 36, true, true WHERE NOT EXISTS (SELECT 1 FROM public.schema_org_places WHERE "locality" IS NOT DISTINCT FROM 'elk' AND "is_global" IS NOT DISTINCT FROM true);

INSERT INTO public.schema_org_page_metadata ("id", "page_slug", "title", "description", "keywords", "is_active", "schema_type", "priority", "change_frequency") SELECT '7b468756-0812-4d46-bd4c-aecb21a68356', 'oferta/konferencje/elk', 'Obsługa konferencji Ełk – technika i streaming | MAVINCI', 'Obsługa konferencji w Ełku: nagłośnienie Meyer Sound, ekrany LED, oświetlenie i streaming. MAVINCI — własna technika i zespół z Olsztyna.', ARRAY[]::text[], true, 'Service', 0.8, 'monthly' WHERE NOT EXISTS (SELECT 1 FROM public.schema_org_page_metadata WHERE "page_slug" IS NOT DISTINCT FROM 'oferta/konferencje/elk');

INSERT INTO public.polish_city_cases ("id", "city_key", "nominative", "genitive", "locative", "locative_preposition", "is_active") SELECT '2fe51f32-f88f-492b-9da9-6a255a573ca4', 'ketrzyn', 'Kętrzyn', 'Kętrzyna', 'Kętrzynie', 'w', true WHERE NOT EXISTS (SELECT 1 FROM public.polish_city_cases WHERE "city_key" IS NOT DISTINCT FROM 'ketrzyn');

INSERT INTO public.schema_org_places ("id", "business_id", "name", "locality", "postal_code", "region", "country", "display_order", "is_active", "is_global") SELECT '7dd7f01c-699d-4ead-98ee-f1924d3c1946', NULL, 'Kętrzyn', 'ketrzyn', '11-400', 'Województwo Warmińsko-Mazurskie', 'PL', 37, true, true WHERE NOT EXISTS (SELECT 1 FROM public.schema_org_places WHERE "locality" IS NOT DISTINCT FROM 'ketrzyn' AND "is_global" IS NOT DISTINCT FROM true);

INSERT INTO public.schema_org_page_metadata ("id", "page_slug", "title", "description", "keywords", "is_active", "schema_type", "priority", "change_frequency") SELECT '9acf8299-7d09-41d6-89ad-73cb69053a5b', 'oferta/konferencje/ketrzyn', 'Obsługa konferencji Kętrzyn – technika i streaming | MAVINCI', 'Obsługa konferencji w Kętrzynie: nagłośnienie Meyer Sound, ekrany LED, oświetlenie i streaming. MAVINCI — własna technika i zespół z Olsztyna.', ARRAY[]::text[], true, 'Service', 0.8, 'monthly' WHERE NOT EXISTS (SELECT 1 FROM public.schema_org_page_metadata WHERE "page_slug" IS NOT DISTINCT FROM 'oferta/konferencje/ketrzyn');

INSERT INTO public.polish_city_cases ("id", "city_key", "nominative", "genitive", "locative", "locative_preposition", "is_active") SELECT 'a4b42f95-ef11-4373-8c87-813a694dbbe7', 'mragowo', 'Mrągowo', 'Mrągowa', 'Mrągowie', 'w', true WHERE NOT EXISTS (SELECT 1 FROM public.polish_city_cases WHERE "city_key" IS NOT DISTINCT FROM 'mragowo');

UPDATE public.schema_org_page_metadata SET "title" = 'Obsługa konferencji Mrągowo – technika i streaming | MAVINCI', "description" = 'Obsługa konferencji w Mrągowie: nagłośnienie Meyer Sound, ekrany LED, oświetlenie i streaming. MAVINCI — własna technika i zespół z Olsztyna.', "keywords" = ARRAY[]::text[] WHERE id = '9331a618-c178-4d00-b9d1-6805a7f225ef' AND "title" IS NOT DISTINCT FROM 'Techniczna Obsługa Konferencji | Ekran LED | Streaming | MAVINCI Event & ART | Mrągowo' AND "description" IS NOT DISTINCT FROM 'Kompleksowa obsługa techniczna konferencji: nagłośnienie, projekcja, streaming, rejestracja wideo. Doświadczenie, profesjonalizm, nowoczesny sprzęt.   ' AND "keywords" IS NOT DISTINCT FROM ARRAY['obsługa konferencji','nagłośnienie konferencji','streaming konferencji','realizacja video','technika konferencyjna','eventy biznesowe','ekran LED','oświetlenie konferencyjne multimedia','multimedia konferencyjne','realizacje AV','realizacja kamerowa','ekrany LED konferencje','obsługa techniczna eventów','technika sceniczna konferencje','profesjonalne nagłośnienie','obsługa wydarzeń','obsługa konferencji Mrągowo','nagłośnienie konferencji Mrągowo','streaming konferencji Mrągowo','realizacje video Mrągowo','technika konferencyjna Mrągowo','eventy biznesowe Mrągowo','ekran LED Mrągowo','oświetlenie konferencyjne multimedia Mrągowo','multimedia konferencyjne Mrągowo','realizacja AV Mrągowo','realizacje kamerowa Mrągowo','ekrany LED konferencje Mrągowo','obsługa techniczna eventów Mrągowo','technika sceniczna konferencje Mrągowo','profesjonalne nagłośnienie Mrągowo','obsługa wydarzeń Mrągowo']::text[];

INSERT INTO public.polish_city_cases ("id", "city_key", "nominative", "genitive", "locative", "locative_preposition", "is_active") SELECT '7ccdb080-139b-4305-a746-eaeaa992fcf4', 'szczytno', 'Szczytno', 'Szczytna', 'Szczytnie', 'w', true WHERE NOT EXISTS (SELECT 1 FROM public.polish_city_cases WHERE "city_key" IS NOT DISTINCT FROM 'szczytno');

UPDATE public.schema_org_page_metadata SET "title" = 'Obsługa konferencji Szczytno – technika i streaming | MAVINCI', "description" = 'Obsługa konferencji w Szczytnie: nagłośnienie Meyer Sound, ekrany LED, oświetlenie i streaming. MAVINCI — własna technika i zespół z Olsztyna.', "keywords" = ARRAY[]::text[] WHERE id = '8ba5d996-9ce7-4b71-bc8d-9a38f93ec203' AND "title" IS NOT DISTINCT FROM 'Techniczna Obsługa Konferencji | Ekran LED | Streaming | MAVINCI Event & ART | Szczytno' AND "description" IS NOT DISTINCT FROM 'Kompleksowa obsługa techniczna konferencji: nagłośnienie, projekcja, streaming, rejestracja wideo. Doświadczenie, profesjonalizm, nowoczesny sprzęt.    ' AND "keywords" IS NOT DISTINCT FROM ARRAY['obsługa konferencji','nagłośnienie konferencji','streaming  konferencji','realizacja video','technika konferencyjna','eventy biznesowe','ekran LED','oświetlenie konferencyjne multimedia','multimedia konferencyjne','realizacja AV','realizacja kamerowa','ekran LED konferencje','obsługa techniczna eventów','technika sceniczna konferencje','profesjonalne nagłośnienie','obsługa wydarzeń','obsługa konferencji Szczytno','nagłośnienie konferencji Szczytno','streaming konferencji Szczytno','realizacja video Szczytno','technika konferencyjna Szczytno','eventy biznesowe Szczytno','ekran LED Szczytno','oświetlenie konferencji multimedia Szczytno','multimedia konferencyjne Szczytno','realizacja AV Szczytno','realizacja kamerowa Szczytno','ekran LED konferencje Szczytno','obsługa techniczna eventów Szczytno','technika sceniczna konferencje Szczytno','profesjonalne nagłośnienie Szczytno','obsługa wydarzeń Szczytno']::text[];

UPDATE public.schema_org_page_metadata SET "title" = 'Obsługa konferencji Elbląg – technika i streaming | MAVINCI', "description" = 'Obsługa konferencji w Elblągu: nagłośnienie Meyer Sound, ekrany LED, oświetlenie i streaming. MAVINCI — własna technika i zespół z Olsztyna.', "keywords" = ARRAY[]::text[] WHERE id = '9140f2f5-d17b-4218-bc17-b1da143e89da' AND "title" IS NOT DISTINCT FROM 'Techniczna Obsługa Konferencji | Ekran LED | Streaming | MAVINCI Event & ART | Elbląg' AND "description" IS NOT DISTINCT FROM 'Kompleksowa obsługa techniczna konferencji: nagłośnienie, projekcja, streaming, rejestracja wideo. Doświadczenie, profesjonalizm, nowoczesny sprzęt.  ' AND "keywords" IS NOT DISTINCT FROM ARRAY['obsługa konferencji','nagłośnienie konferencji','streaming konferencji','realizacja video','technika konferencyjna','eventy biznesowe','ekran LED','oświetlenie konferencyjne multimedia','multimedia konferencyjne','realizacja AV','realizacja kamerowa','ekrany LED konferencje','obsługa techniczna eventów','technika sceniczna konferencje','profesjonalne nagłośnienie','obsługa wydarzeń','obsługa konferencji Elbląg','nagłośnienie konferencji Elbląg','streaming konferencji Elbląg','realizacja video Elbląg','technika konferencyjna Elbląg','eventy biznesowe Elbląg','ekran LED Elbląg','oświetlenie konferencyjne multimedia Elbląg','multimedia konferencyjne Elbląg','realizacja AV Elbląg','realizacja kamerowa Elbląg','ekran LED konferencje Elbląg','obsługa techniczna eventów Elbląg','technika sceniczna konferencji Elbląg','profesjonalne nagłośnienie Elbląg','obsługa wydarzeń Elbląg']::text[];

UPDATE public.schema_org_page_metadata SET "title" = 'Obsługa konferencji Mikołajki – technika i streaming | MAVINCI', "description" = 'Obsługa konferencji w Mikołajkach: nagłośnienie Meyer Sound, ekrany LED, oświetlenie i streaming. MAVINCI — własna technika i zespół z Olsztyna.', "keywords" = ARRAY[]::text[] WHERE id = 'dc176e9f-d626-4e24-9f2a-7ab0c0517f2f' AND "title" IS NOT DISTINCT FROM 'Obsługa Konferencji Mikołajki | Nagłośnienie, Streaming, Multimedia | Mavinci' AND "description" IS NOT DISTINCT FROM 'Kompleksowa obsługa konferencji w Mikołajkach. Nagłośnienie, oświetlenie, multimedia, streaming, realizacja obrazu, sceny oraz pełne zaplecze techniczne dla wydarzeń biznesowych i konferencji.' AND "keywords" IS NOT DISTINCT FROM ARRAY['obsługa konferencji Mikołajki','techniczna obsługa konferencji Mikołajki','konferencje Mikołajki','organizacja konferencji Mikołajki','nagłośnienie konferencji Mikołajki','oświetlenie konferencji Mikołajki','multimedia konferencyjne Mikołajki','streaming konferencji Mikołajki','transmisja konferencji Mikołajki','realizacja obrazu Mikołajki','obsługa techniczna eventów Mikołajki','konferencje Mazury','obsługa konferencji Mazury','nagłośnienie eventów Mikołajki','scena konferencyjna Mikołajki','telebimy Mikołajki','ekrany LED Mikołajki','realizacja konferencji Mikołajki','eventy biznesowe Mikołajki','Mavinci konferencje Mikołajki']::text[];

UPDATE public.conferences_case_studies SET "is_active" = false WHERE id = '6ca365d2-91a4-4776-9459-5c9a794d7d5c' AND "is_active" IS NOT DISTINCT FROM true;

UPDATE public.conferences_case_studies SET "is_active" = false WHERE id = 'b6a80b28-c24a-4d0d-be64-e0cb44b50e4d' AND "is_active" IS NOT DISTINCT FROM true;

UPDATE public.conferences_case_studies SET "is_active" = false WHERE id = '787455c1-bbb8-4ce4-825f-4413bf52878d' AND "is_active" IS NOT DISTINCT FROM true;

UPDATE public.conferences_service_items SET "name" = 'Ekrany LED do konferencji i gal', "description" = 'Ekrany LED, prezentacje i realizacja obrazu podczas konferencji, gal i eventów.', "long_description" = 'Własne ekrany LED MAVINCI do konferencji, gal i wydarzeń firmowych. Przygotowujemy obraz dla prezentacji, materiałów wideo i oprawy sceny, a format ekranu dobieramy do przestrzeni oraz scenariusza. Zapewniamy przygotowanie, montaż i obsługę multimediów. Pracujemy z Olsztyna na Warmii i Mazurach oraz przy realizacjach w innych regionach Polski. Szczegółową konfigurację ekranu i wymagania techniczne potwierdzamy w ofercie.', "seo_title" = 'Ekrany LED na konferencje i gale Olsztyn | MAVINCI', "seo_description" = 'Ekrany LED, prezentacje i multimedia na konferencje, gale oraz eventy. Własne zaplecze MAVINCI w Olsztynie. Realizacje na Warmii i Mazurach.', "seo_keywords" = 'ekrany LED Olsztyn, ekrany LED konferencje, multimedia Warmia Mazury', "features" = ARRAY['Własne ekrany LED','Format dobierany do przestrzeni i programu','Obsługa prezentacji i materiałów wideo','Montaż i realizacja multimediów']::text[], "technical_specs" = '{"Zastosowanie": "Konferencje, gale i wydarzenia firmowe", "Konfiguracja": "Format i parametry potwierdzane w indywidualnej ofercie"}'::jsonb WHERE id = 'b1dc8e24-a4c2-4d74-bf39-7ac36a83e550' AND "name" IS NOT DISTINCT FROM 'Ekrany LED do konferencji i gall' AND "description" IS NOT DISTINCT FROM 'Duże formaty LED do prezentacji i eventów premium' AND "long_description" IS NOT DISTINCT FROM 'Ściany LED premium do konferencji i gal. Duże formaty ekranów LED tworzące efektowne tło dla prezentacji, koncertów i eventów korporacyjnych. Możliwość realizacji ścian od 3x2m do 10x6m.' AND "seo_title" IS NOT DISTINCT FROM 'LED do Konferencji i Gal - Wynajem | MAVINCI' AND "seo_description" IS NOT DISTINCT FROM 'Duże ściany LED premium do eventów. Formaty od 3x2m do 10x6m, pitch 2.9-4mm, wsparcie 4K/8K. Warszawa, Gdańsk.' AND "seo_keywords" IS NOT DISTINCT FROM 'ściana led konferencja, ściana led event, duży ekran led, tło led scena, led wall wynajem' AND "features" IS NOT DISTINCT FROM ARRAY['Formaty od 3x2m do 10x6m','Pitch 2.6mm','Brak widocznych łączeń','Profesjonalna kalibracja kolorów']::text[] AND "technical_specs" IS NOT DISTINCT FROM '{"depth": "80mm", "pitch": "2.9mm - 4mm", "refresh": "3840Hz", "brightness": "1500 nits", "Rozmiar Kabinetu": "500x500mm"}'::jsonb;

UPDATE public.schema_org_page_metadata SET "title" = 'Ekrany LED na konferencje i gale Olsztyn | MAVINCI', "description" = 'Ekrany LED, prezentacje i multimedia na konferencje, gale oraz eventy. Własne zaplecze MAVINCI w Olsztynie. Realizacje na Warmii i Mazurach.' WHERE id = 'dd3e4f59-ef4e-4c23-98b9-0b03519edfbe' AND "title" IS NOT DISTINCT FROM 'Ściankii' AND "description" IS NOT DISTINCT FROM NULL;

UPDATE public.conferences_service_items SET "seo_title" = 'Realizacja wielokamerowa i streaming Olsztyn | MAVINCI', "seo_description" = 'Realizacja wielokamerowa konferencji, gal i wydarzeń firmowych. Operatorzy, reżyseria wizji i nagrania. MAVINCI Olsztyn — Warmia i Mazury.' WHERE id = 'bab36a69-f61a-4403-9695-84280b2b9e91' AND "seo_title" IS NOT DISTINCT FROM 'Realizacja Wielokamerowa (Multicam) – Profesjonalna Obsługa Eventów | MAVINCI' AND "seo_description" IS NOT DISTINCT FROM 'Profesjonalna realizacja wielokamerowa (multicam) na eventy, konferencje i gale. Dynamiczne ujęcia, operatorzy kamer, reżyseria live i pełna kontrola nad obrazem. Idealne do streamingu, nagrań i transmisji online.';

UPDATE public.schema_org_page_metadata SET "title" = 'Realizacja wielokamerowa i streaming Olsztyn | MAVINCI', "description" = 'Realizacja wielokamerowa konferencji, gal i wydarzeń firmowych. Operatorzy, reżyseria wizji i nagrania. MAVINCI Olsztyn — Warmia i Mazury.', "keywords" = ARRAY[]::text[] WHERE id = '83360a2b-611d-4d4a-9621-6a67d6d2389f' AND "title" IS NOT DISTINCT FROM 'Realizacja wielokamerowa - MAVINCI Event & ART' AND "description" IS NOT DISTINCT FROM 'Od 2 do 6 kamer z pełną reżyserką' AND "keywords" IS NOT DISTINCT FROM ARRAY['realizacja wielokamerowa','wynajem','eventy','konferencje']::text[];

UPDATE public.conferences_service_items SET "name" = 'Nagłośnienie Meyer Sound LINA', "description" = 'Własny system line-array Meyer Sound LINA z obsługą realizatorską.', "long_description" = 'MAVINCI dysponuje własnym systemem nagłośnieniowym Meyer Sound LINA. Zapewniamy dobór konfiguracji, przygotowanie i realizację dźwięku podczas konferencji, koncertów, gal i wydarzeń firmowych. Wielkość systemu dobieramy do akustyki obiektu, układu publiczności i wymagań programu. Nasza baza znajduje się przy ul. Towarowej 20B w Olsztynie. Obsługujemy Warmię i Mazury oraz wydarzenia w innych regionach Polski.', "seo_title" = 'Nagłośnienie Meyer Sound LINA Olsztyn | MAVINCI', "seo_description" = 'Własny system Meyer Sound LINA i realizacja dźwięku na konferencje, koncerty i gale. MAVINCI Olsztyn — obsługa Warmii i Mazur oraz wydarzeń w Polsce.', "seo_keywords" = 'Meyer Sound LINA, nagłośnienie Olsztyn, technika eventowa Warmia Mazury', "features" = ARRAY['Własny system Meyer Sound LINA','Dobór konfiguracji do miejsca i programu','Montaż i realizacja dźwięku','Obsługa konferencji, koncertów i gal']::text[], "technical_specs" = '{"Producent": "Meyer Sound", "Model": "LINA", "Typ": "Line array", "Konfiguracja": "Dobierana do projektu"}'::jsonb WHERE id = '8b02f14c-1883-4bb0-b88c-bf8fae04c91b' AND "name" IS NOT DISTINCT FROM 'Systemy line-array Meyer Sound - LINA' AND "description" IS NOT DISTINCT FROM 'Premium nagłośnienie dla dużych konferencji i eventów' AND "long_description" IS NOT DISTINCT FROM 'System nagłośnieniowy Meyer Sound - LINAy - topowy line-array dla dużych konferencji, koncertów i eventów premium. Krystalicznie czysty dźwięk, ogromna moc i precyzyjne pokrycie akustyczne. Idealny dla sal od 500 do 5000 osób.' AND "seo_title" IS NOT DISTINCT FROM 'Nagłośnienie Meyer Sound - LINA - Wynajem | MAVINCI' AND "seo_description" IS NOT DISTINCT FROM 'Premium nagłośnienie Meyer Sound - LINA line-array do wynajęcia. 130dB SPL, pokrycie do 5000 osób. Warszawa, Gdańsk, Bydgoszcz.' AND "seo_keywords" IS NOT DISTINCT FROM 'coda audio, line array wynajem, nagłośnienie premium, nagłośnienie konferencja, system line array' AND "features" IS NOT DISTINCT FROM ARRAY['Meyer Sound - LINA','130dB SPL max','Pokrycie do 5000 osób','Precyzyjne targetowanie akustyczne']::text[] AND "technical_specs" IS NOT DISTINCT FROM '{"type": "Line Array", "weight": "29kg", "spl_max": "130dB", "coverage": "90° x 10°", "amplifier": "Class D 2000W", "frequency": "50Hz - 18kHz"}'::jsonb;

INSERT INTO public.schema_org_page_metadata ("id", "page_slug", "title", "description", "keywords", "is_active", "schema_type", "priority", "change_frequency") SELECT 'b89f2fb3-1d8a-44fc-a58d-eeb64886260e', 'uslugi/systemy-line-array-meyer-sound-lina', 'Nagłośnienie Meyer Sound LINA Olsztyn | MAVINCI', 'Własny system Meyer Sound LINA i realizacja dźwięku na konferencje, koncerty i gale. MAVINCI Olsztyn — obsługa Warmii i Mazur oraz wydarzeń w Polsce.', ARRAY[]::text[], true, 'Service', 0.8, 'monthly' WHERE NOT EXISTS (SELECT 1 FROM public.schema_org_page_metadata WHERE "page_slug" IS NOT DISTINCT FROM 'uslugi/systemy-line-array-meyer-sound-lina');

UPDATE public.portfolio_projects SET "location" = 'Hotel Przystań, Olsztyn', "meta_description" = 'Konferencja PSRWN w Hotelu Przystań w Olsztynie: obsługa techniczna MAVINCI, streaming i oprawa bankietu. Zobacz zakres realizacji i zdjęcia.' WHERE id = '3b3bb671-c81f-4033-a71e-8012c1f9f88c' AND "location" IS NOT DISTINCT FROM 'Polska' AND "meta_description" IS NOT DISTINCT FROM NULL;

UPDATE public.conferences_hero SET "title" = 'Obsługa konferencji z własnym zapleczem technicznym', "subtitle" = 'Nagłośnienie Meyer Sound, ekrany LED, oświetlenie, multimedia i streaming. MAVINCI Olsztyn — technika i realizacja wydarzeń biznesowych.', "trust_badge" = 'Własna technika w Olsztynie. Realizacje na Warmii i Mazurach oraz w Polsce.' WHERE id = '1a76d5a1-cf39-404d-b010-10d157b6886b' AND "title" IS NOT DISTINCT FROM 'Kompleksowa obsługa techniczna konferencji' AND "subtitle" IS NOT DISTINCT FROM 'Profesjonalne nagłośnienie, multimedia i realizacja live. Od małych spotkań po konferencje dla 500+ uczestników.' AND "trust_badge" IS NOT DISTINCT FROM 'Obsługujemy wydarzenia w północnej i centralnej Polsce';

-- Older databases regenerate slugs on title edits. Preserve the two established URLs.
UPDATE public.conferences_service_items SET slug = 'ekrany-led-do-konferencji-i-gall'
WHERE id = 'b1dc8e24-a4c2-4d74-bf39-7ac36a83e550' AND name = 'Ekrany LED do konferencji i gal' AND slug = 'ekrany-led-do-konferencji-i-gal';
UPDATE public.conferences_service_items SET slug = 'systemy-line-array-meyer-sound-lina'
WHERE id = '8b02f14c-1883-4bb0-b88c-bf8fae04c91b' AND name = 'Nagłośnienie Meyer Sound LINA' AND slug = 'naglosnienie-meyer-sound-lina';

COMMIT;
