/*
  # Startowa tresc kart produktow

  Uzupelnia wyłącznie puste pola prezentacyjne. Ponowne wykonanie migracji
  nie nadpisze tresci zatwierdzonej pozniej przez pracownika CRM.
*/

WITH product_copy (id, short_description, full_description, benefits) AS (
  VALUES
    ('92783440-9a5d-484c-86c0-0560a470fcc0'::uuid,
      'Dekoracje dobrane do charakteru wydarzenia i wybranej przestrzeni.',
      'Wynajem dekoracji pozwala spójnie uzupełnić aranżację sali lub wybranej strefy wydarzenia. Zakres elementów oraz sposób ich wykorzystania ustalamy odpowiednio do miejsca, motywu i potrzeb organizatora.',
      jsonb_build_array('Spójna oprawa wizualna wydarzenia', 'Dobór elementów do miejsca i motywu', 'Elastyczny zakres wynajmu')),
    ('3bbb8f85-f667-4b59-8e62-c61813a40324'::uuid,
      'Prowadzenie wydarzenia w uporządkowany, angażujący i dopasowany do gości sposób.',
      'Konferansjer dba o płynny przebieg programu, zapowiada jego kolejne części i utrzymuje kontakt z uczestnikami. Styl prowadzenia ustalamy zgodnie z charakterem wydarzenia oraz oczekiwaniami organizatora.',
      jsonb_build_array('Spójny przebieg programu', 'Czytelna komunikacja z uczestnikami', 'Styl dopasowany do wydarzenia')),
    ('a7b088cc-d974-4909-9e2d-04d0f7bfc337'::uuid,
      'Klubowy set DJ-ski dopasowany do charakteru imprezy i energii uczestników.',
      'DJ klubowy przygotowuje i prowadzi oprawę muzyczną nastawioną na dynamiczny charakter wydarzenia. Repertuar i tempo setu są dobierane do profilu imprezy oraz reakcji publiczności.',
      jsonb_build_array('Dynamiczna oprawa muzyczna', 'Repertuar dopasowany do publiczności', 'Płynne prowadzenie części tanecznej')),
    ('99c75f00-c0b5-4ce3-86d1-88b0a4d0f758'::uuid,
      'Oprawa muzyczna połączona z czytelnymi zapowiedziami najważniejszych punktów wydarzenia.',
      'DJ i prezenter muzyczny odpowiada za dobór muzyki oraz komunikaty potrzebne podczas imprezy. Forma prowadzenia pozostaje dopasowana do scenariusza, gości i oczekiwanego poziomu interakcji.',
      jsonb_build_array('Muzyka i zapowiedzi w jednej usłudze', 'Płynna realizacja scenariusza', 'Dobór repertuaru do uczestników')),
    ('00f4e2f5-baae-4222-a19d-9030452ddf3a'::uuid,
      'Kompletna podstawowa oprawa DJ-ska wydarzenia.',
      'Pakiet DJ Standard obejmuje prowadzenie oprawy muzycznej z podstawowym stanowiskiem DJ-skim. Repertuar oraz sposób pracy są dopasowywane do rodzaju wydarzenia i ustalonego programu.',
      jsonb_build_array('Kompletna podstawowa oprawa muzyczna', 'Repertuar dopasowany do wydarzenia', 'Sprawne prowadzenie części tanecznej')),
    ('d9cd5444-76e9-4781-8669-6c698815a573'::uuid,
      'Oprawa muzyczna DJ w wariancie FOCUS, dopasowana do przebiegu wydarzenia.',
      'DJ Standard – FOCUS zapewnia prowadzenie muzycznej części wydarzenia w uzgodnionej formule. Szczegóły repertuaru, harmonogramu i zakresu technicznego są ustalane przed realizacją.',
      jsonb_build_array('Uzgodniona formuła oprawy muzycznej', 'Dobór repertuaru do gości', 'Zakres dopasowany do harmonogramu')),
    ('9233cd77-6da4-4990-b914-f3c0a924f3e0'::uuid,
      'Interaktywna atrakcja fotograficzna, która angażuje gości i tworzy pamiątkowe ujęcia.',
      'Fotolustro stanowi samodzielną strefę atrakcji podczas wydarzenia. Uczestnicy mogą wykonywać zdjęcia w swobodnej formule, a wygląd i zakres stanowiska dobieramy do charakteru realizacji.',
      jsonb_build_array('Atrakcja dostępna przez wydarzenie', 'Naturalna integracja uczestników', 'Pamiątkowe zdjęcia dla gości')),
    ('8402d5b0-12cd-4a4d-adb3-0997d5f08658'::uuid,
      'Bieżąca realizacja oświetlenia dopasowana do programu i dynamiki wydarzenia.',
      'Realizator oświetlenia przygotowuje i prowadzi pracę systemu świetlnego podczas wydarzenia. Na bieżąco dopasowuje sceny oraz zmiany światła do programu, muzyki i sytuacji na sali.',
      jsonb_build_array('Spójna praca oświetlenia z programem', 'Bieżąca reakcja na przebieg wydarzenia', 'Techniczny nadzór nad systemem świetlnym')),
    ('32072a07-439e-4942-9b97-5ea2b60e4f89'::uuid,
      'Klimatyczna strefa rozrywki inspirowana klasycznym kasynem.',
      'Strefa kasynowa wprowadza uczestników w elegancką konwencję zabawy i tworzy naturalne miejsce integracji. Liczbę stanowisk oraz zakres aranżacji dopasowujemy do przestrzeni i liczby gości.',
      jsonb_build_array('Wyrazisty motyw przewodni', 'Swobodna integracja uczestników', 'Skalowalny zakres strefy')),
    ('2b5d40de-34bd-4576-b43f-5073053183f3'::uuid,
      'Autorski teleturniej zespołowy łączący rywalizację, humor i aktywny udział gości.',
      'Teleturniej Mavimbury angażuje uczestników w zadania prowadzone w formule drużynowej. Przebieg i poziom trudności dopasowujemy do grupy, czasu dostępnego w programie oraz charakteru wydarzenia.',
      jsonb_build_array('Aktywny udział uczestników', 'Integracja przez drużynową rywalizację', 'Formuła dopasowana do grupy')),
    ('97f1a89b-3f8e-404e-b11c-0062828a8e0b'::uuid,
      'Tematyczna oprawa wydarzenia inspirowana stylem lat 20. i światem Wielkiego Gatsbyego.',
      'Wieczór Gatsby tworzy elegancki motyw przewodni dla wydarzenia firmowego lub integracyjnego. Zakres programu i elementów oprawy dobieramy do miejsca, liczby uczestników i oczekiwanego charakteru spotkania.',
      jsonb_build_array('Rozpoznawalny motyw wydarzenia', 'Spójny klimat i oprawa', 'Zakres dostosowany do przestrzeni')),
    ('a5b560f3-2179-4d81-95ad-668c0f53c389'::uuid,
      'Około 45-minutowy występ stand-upowy jako wyrazisty punkt programu.',
      'Występ artystyczny w formule stand-upu uzupełnia wydarzenie o samodzielny blok rozrywkowy. Dobór artysty i charakter materiału są uzgadniane z uwzględnieniem profilu publiczności oraz rodzaju spotkania.',
      jsonb_build_array('Gotowy punkt programu', 'Forma angażująca publiczność', 'Dobór występu do charakteru wydarzenia')),
    ('a2e0f5c2-d575-402e-bbf7-8e79e7696eb9'::uuid,
      'Kolorowa dmuchana zjeżdżalnia w motywie Psiego Patrolu dla najmłodszych uczestników.',
      'Dmuchana zjeżdżalnia tworzy atrakcyjną strefę aktywności podczas festynu lub wydarzenia rodzinnego. Miejsce ustawienia i warunki realizacji każdorazowo weryfikujemy pod kątem dostępnej przestrzeni.',
      jsonb_build_array('Widoczna atrakcja dla dzieci', 'Aktywna forma zabawy', 'Tematyka znana najmłodszym uczestnikom')),
    ('33014d16-56d8-44ca-a342-515cabff53a7'::uuid,
      'Koordynacja formalności licencyjnych wymaganych dla uzgodnionego zakresu wydarzenia.',
      'Obsługa licencji porządkuje kwestie formalne związane z wykorzystaniem materiałów objętych ochroną. Zakres usługi jest ustalany na podstawie programu, miejsca i sposobu realizacji wydarzenia.',
      jsonb_build_array('Uporządkowanie wymaganych formalności', 'Zakres dopasowany do programu', 'Jeden punkt koordynacji procesu')),
    ('b2d55061-6eb1-4576-8727-bd0db5052850'::uuid,
      'Muzyczny występ w klimacie żeglarskim, sprzyjający wspólnemu śpiewaniu i integracji.',
      'Szantyman prowadzi koncertowy lub biesiadny blok oparty na repertuarze żeglarskim. Forma występu może zostać dopasowana do charakteru wydarzenia, miejsca i przewidzianego czasu programu.',
      jsonb_build_array('Wyrazisty żeglarski klimat', 'Bezpośredni kontakt z publicznością', 'Naturalna integracja przy muzyce')),
    ('a3e4908f-e867-49c3-ac59-a4967c7bb38f'::uuid,
      'Koncertowa oprawa w swingowym charakterze w wykonaniu Warmia Swing.',
      'Występ Warmia Swing stanowi elegancki, samodzielny punkt programu muzycznego. Długość i formułę występu uzgadniamy odpowiednio do harmonogramu oraz charakteru wydarzenia.',
      jsonb_build_array('Swingowy charakter oprawy', 'Gotowy blok koncertowy', 'Formuła dopasowana do harmonogramu')),
    ('87e09803-e9bd-48eb-9f91-0e8c50b388e4'::uuid,
      'Stanowisko zapewniające warunki do realizacji tłumaczenia symultanicznego podczas konferencji.',
      'Kabina symultaniczna wydziela miejsce pracy tłumacza i wspiera organizację wielojęzycznego wydarzenia. Konfigurację dobieramy do sali, liczby języków oraz pozostałego systemu konferencyjnego.',
      jsonb_build_array('Wydzielone stanowisko dla tłumacza', 'Wsparcie wydarzeń wielojęzycznych', 'Konfiguracja dopasowana do sali')),
    ('19845058-0541-43c9-a222-f46fe0f327e7'::uuid,
      'Kompleksowy nadzór techniczny nad przebiegiem konferencji.',
      'Obsługa techniczna konferencji obejmuje przygotowanie i bieżącą koordynację uzgodnionych systemów podczas wydarzenia. Zakres zespołu dobieramy do programu, sali oraz wykorzystywanego nagłośnienia, obrazu i transmisji.',
      jsonb_build_array('Jeden zespół koordynujący technikę', 'Bieżące wsparcie podczas programu', 'Zakres dopasowany do skali konferencji')),
    ('be81ab60-9ca7-4429-af94-b7068f8e9530'::uuid,
      'Modułowy podest sceniczny dopasowany do potrzeb prezentacji i układu sali.',
      'Podest sceniczny porządkuje przestrzeń wystąpień i poprawia widoczność osoby prezentującej. Wymiary oraz konfigurację ustalamy odpowiednio do miejsca, programu i dostępnej powierzchni.',
      jsonb_build_array('Lepsza widoczność strefy wystąpień', 'Konfiguracja do układu sali', 'Czytelne wydzielenie sceny')),
    ('bcd38877-b15f-434e-aec5-d9c6bc8af5b4'::uuid,
      'Element systemu multimedialnego dobierany do konfiguracji konkretnej realizacji.',
      'Dioda uzupełnia uzgodniony zestaw multimedialny wydarzenia. Jej dokładne zastosowanie i liczba wynikają z projektu technicznego oraz potrzeb obrazu przygotowanego dla danej przestrzeni.',
      jsonb_build_array('Uzupełnienie konfiguracji multimedialnej', 'Dobór do projektu technicznego', 'Elastyczna liczba elementów')),
    ('137230df-baf9-41af-8ee8-ff6b18148668'::uuid,
      'Modułowy ekran LED konfigurowany w wymiarze odpowiednim do przestrzeni i treści.',
      'Ekran LED budowany z modułów pozwala dobrać powierzchnię obrazu do układu sceny oraz odległości widzów. Liczba metrów kwadratowych i proporcje ekranu są ustalane dla konkretnej realizacji.',
      jsonb_build_array('Rozmiar dopasowany do miejsca', 'Czytelna prezentacja materiałów', 'Elastyczna konfiguracja modułowa')),
    ('2c595604-4691-4a5f-bc08-842ae3db9423'::uuid,
      'Fotograficzna dokumentacja najważniejszych momentów wydarzenia.',
      'Fotoreportaż obejmuje pracę fotografa podczas uzgodnionej części wydarzenia oraz przygotowanie materiału oddającego jego przebieg i atmosferę. Zakres godzinowy i oczekiwane ujęcia ustalamy przed realizacją.',
      jsonb_build_array('Dokumentacja przebiegu wydarzenia', 'Naturalne ujęcia uczestników i detali', 'Zakres ustalony przed realizacją')),
    ('4330d789-302c-4439-b3d2-3e82dc71b28e'::uuid,
      'Kompleksowa realizacja transmisji online dla uczestników łączących się zdalnie.',
      'Zapewniamy przygotowanie i obsługę techniczną transmisji wydarzenia do wskazanej platformy, z wykorzystaniem kamer oraz sygnału prezentacji. Realizacja obejmuje konfigurację obrazu i bieżący nadzór techniczny, dzięki czemu uczestnicy zdalni mogą czytelnie śledzić przebieg spotkania.',
      jsonb_build_array('Czytelny obraz dla uczestników zdalnych', 'Możliwość łączenia obrazu z kamer i prezentacji', 'Bieżąca obsługa techniczna podczas transmisji')),
    ('720e6b91-b36f-4c12-bc5c-14bce8bdb9ba'::uuid,
      'Duży ekran 65 cali do prezentacji materiałów, podglądu lub informacji dla uczestników.',
      'Telewizor 65 cali zapewnia czytelny obraz w mniejszych salach, strefach pomocniczych lub na stanowiskach podglądowych. Sposób ustawienia i źródło sygnału dobieramy do układu wydarzenia.',
      jsonb_build_array('Czytelny obraz w wydzielonej strefie', 'Uniwersalne zastosowanie', 'Łatwe dopasowanie do układu sali')),
    ('d250e18e-6c9c-45e4-a8c9-ade35a1fa9c0'::uuid,
      'System nagłośnienia typu point source dobierany do charakteru i układu wydarzenia.',
      'Nagłośnienie point source zapewnia kierunkowe pokrycie dźwiękiem w konfiguracji przygotowanej dla konkretnej przestrzeni. Liczbę zestawów i sposób rozmieszczenia ustalamy na podstawie sali, publiczności oraz programu.',
      jsonb_build_array('Konfiguracja dopasowana do przestrzeni', 'Czytelna emisja mowy i muzyki', 'Skalowalny zakres systemu')),
    ('3c62a5c3-a79a-41db-bf9f-55b363227cfe'::uuid,
      'Profesjonalna realizacja dźwięku i bieżący nadzór nad systemem nagłośnienia.',
      'Realizator nagłośnienia przygotowuje system, kontroluje poziomy i reaguje na przebieg wydarzenia. Dba o czytelność mowy, materiałów audio oraz sprawną współpracę z osobami występującymi.',
      jsonb_build_array('Bieżąca kontrola jakości dźwięku', 'Wsparcie osób występujących', 'Nadzór nad systemem przez wydarzenie')),
    ('f21a0de2-0c71-42bf-b059-8aeab50667aa'::uuid,
      'Przygodowy scenariusz integracyjny inspirowany klimatem ekspedycji i wspólnego odkrywania.',
      'Indiana Jones angażuje zespoły w serię zadań wymagających współpracy, komunikacji i wspólnego podejmowania decyzji. Szczegółowy przebieg dopasowujemy do liczby uczestników, czasu oraz miejsca wydarzenia.',
      jsonb_build_array('Współpraca w zespołach', 'Angażujący motyw przygodowy', 'Scenariusz dopasowany do grupy')),
    ('6e4009ae-3d54-4045-9ad5-c3992b0e95ec'::uuid,
      'Zespołowe zadanie integracyjne oparte na wspólnym planowaniu i koordynacji działań.',
      'Megaklucz stawia przed uczestnikami wspólny cel, którego realizacja wymaga komunikacji i podziału ról. Formułę zadania dobieramy do liczby osób oraz miejsca przeprowadzenia aktywności.',
      jsonb_build_array('Ćwiczenie komunikacji', 'Wspólne dążenie do celu', 'Aktywny udział całego zespołu')),
    ('7e790778-e5fb-41de-b9a0-c513bc945594'::uuid,
      'Integracyjne zadanie pamięciowe rozwijające koncentrację i współpracę zespołu.',
      'Memo wykorzystuje prostą, angażującą formułę pracy ze skojarzeniami i pamięcią. Uczestnicy działają wspólnie, wymieniają informacje i wypracowują sposób skutecznego wykonania zadania.',
      jsonb_build_array('Trening koncentracji i pamięci', 'Wymiana informacji w zespole', 'Przystępna forma rywalizacji')),
    ('de22e432-3c52-48ea-ac48-748fb7582392'::uuid,
      'Nieszablonowe zadanie zespołowe wymagające komunikacji i wspólnego rozwiązania problemu.',
      'Operacja Kaczka angażuje uczestników w integracyjną misję realizowaną w grupie. Szczegóły zadania i poziom trudności dopasowujemy do liczby osób, miejsca oraz dostępnego czasu.',
      jsonb_build_array('Wspólne rozwiązywanie problemu', 'Aktywna komunikacja', 'Scenariusz dopasowany do grupy')),
    ('6c63be39-4c90-40a9-90d0-fafb35c7de5c'::uuid,
      'Zadanie integracyjne, w którym skuteczna komunikacja zastępuje pełny dostęp do informacji.',
      'Ślepe Abecadło wymaga od uczestników precyzyjnego przekazywania wskazówek i uważnego słuchania. Ćwiczenie pokazuje znaczenie jasnych komunikatów oraz współpracy w osiąganiu wspólnego celu.',
      jsonb_build_array('Ćwiczenie precyzyjnej komunikacji', 'Budowanie zaufania w zespole', 'Wspólna realizacja zadania')),
    ('c6ad0596-f006-43bd-8405-9603cb7023ec'::uuid,
      'Drużynowa wersja klasycznej gry, nastawiona na planowanie i współpracę.',
      'Tic Tac Toe przenosi znaną mechanikę do zespołowej aktywności integracyjnej. Uczestnicy wspólnie ustalają strategię, reagują na decyzje drugiej drużyny i dzielą się rolami.',
      jsonb_build_array('Proste zasady i szybkie zaangażowanie', 'Wspólne planowanie strategii', 'Przyjazna rywalizacja drużynowa')),
    ('34a8cf22-dde0-495b-9f4d-c88ce9ff620b'::uuid,
      'Logiczne wyzwanie zespołowe oparte na analizie informacji i wspólnym wnioskowaniu.',
      'Zagadka Einsteina angażuje uczestników w uporządkowanie danych i znalezienie rozwiązania poprzez współpracę. Zadanie wspiera podział ról, argumentowanie oraz łączenie różnych perspektyw.',
      jsonb_build_array('Rozwijanie logicznego myślenia', 'Wspólna analiza informacji', 'Zaangażowanie różnych kompetencji')),
    ('41496fb9-0a95-462b-bdd8-b5a61a7953f4'::uuid,
      'Konstrukcyjne zadanie integracyjne wymagające koordynacji i zrozumienia zależności.',
      'Zębate Koła angażują zespół w przygotowanie wspólnie działającego rozwiązania. Uczestnicy planują kolejne działania, dzielą się odpowiedzialnością i sprawdzają wpływ poszczególnych elementów na rezultat.',
      jsonb_build_array('Wspólne planowanie i budowanie', 'Widoczny efekt pracy zespołu', 'Ćwiczenie koordynacji działań')),
    ('b6b4d895-5253-486a-9bae-909044564a2a'::uuid,
      'Efekt dymny przygotowany jako krótki, wyrazisty element oprawy wydarzenia.',
      'Usługa obejmuje realizację uzgodnionego efektu dymnego w odpowiednim momencie programu. Sposób użycia i warunki techniczne są dobierane do miejsca oraz pozostałej oprawy.',
      jsonb_build_array('Wyraziste podkreślenie momentu', 'Realizacja zsynchronizowana z programem', 'Zakres dobrany do miejsca')),
    ('3794a340-c98a-4949-a51a-6d10b94dbed7'::uuid,
      'Lekka i efektowna oprawa z baniek mydlanych do wybranych momentów uroczystości.',
      'Bańki mydlane tworzą dekoracyjny efekt dobrze widoczny na żywo i na zdjęciach. Moment oraz miejsce realizacji ustalamy z uwzględnieniem przebiegu wydarzenia i warunków przestrzeni.',
      jsonb_build_array('Subtelny efekt wizualny', 'Atrakcyjne tło dla zdjęć', 'Możliwość dopasowania do programu')),
    ('539bf83c-354d-45e8-adfd-a9bb21b1e174'::uuid,
      'Dekoracyjne oprawy Portman P1 Evo budujące elegancki klimat światłem.',
      'Portman P1 Evo łączy funkcję dekoracji z ciepłą oprawą świetlną przestrzeni. Liczbę urządzeń i ich rozmieszczenie dobieramy do układu sali, sceny lub strefy tanecznej.',
      jsonb_build_array('Dekoracyjny charakter światła', 'Efektowny wygląd również bez ruchu', 'Rozmieszczenie dopasowane do sali')),
    ('bdc2b45e-d856-4c91-834a-4287a4a10989'::uuid,
      'Rozbudowana dekoracja sali światłem z wykorzystaniem 40 punktów świetlnych.',
      'Pakiet pozwala podkreślić architekturę, ściany i wybrane strefy wydarzenia spójnym kolorem światła. Rozmieszczenie 40 punktów ustalamy na podstawie układu sali i oczekiwanego efektu.',
      jsonb_build_array('Spójna zmiana charakteru sali', 'Podkreślenie architektury i dekoracji', 'Rozbudowany zakres 40 punktów')),
    ('72f78e8d-78da-401b-834a-5da66f36a3d4'::uuid,
      'Drużynowy teleturniej weselny angażujący gości w lekką i humorystyczną zabawę.',
      'Familiada wprowadza do programu interaktywną rywalizację prowadzoną w przystępnej formule. Pytania i przebieg zabawy można dopasować do charakteru uroczystości oraz uczestników.',
      jsonb_build_array('Aktywny udział gości', 'Lekka rywalizacja drużynowa', 'Punkt programu dopasowany do wesela')),
    ('cbdd905d-37d9-4f33-aefb-b717c6f7a7bc'::uuid,
      'DJ, wodzirej i akordeonista tworzący wspólną, różnorodną oprawę wesela.',
      'Flagowe Trio łączy prowadzenie muzyczne DJ-a, kontakt wodzireja z gośćmi oraz brzmienie akordeonu. Taki skład pozwala płynnie przechodzić między zabawą taneczną, zapowiedziami i muzycznymi akcentami na żywo.',
      jsonb_build_array('Trzy uzupełniające się role', 'Muzyka mechaniczna i akcenty na żywo', 'Aktywne prowadzenie zabawy')),
    ('a0ba0b0d-0535-4d45-b89f-fd29a81b6b01'::uuid,
      'Dwie sceniczne fontanny iskier podkreślające wybrany moment uroczystości.',
      'Zestaw dwóch fontann iskier tworzy symetryczny efekt wizualny podczas pierwszego tańca, wejścia lub innego uzgodnionego punktu programu. Ustawienie i moment uruchomienia są wcześniej koordynowane z obsługą wydarzenia.',
      jsonb_build_array('Symetryczny efekt dwóch urządzeń', 'Podkreślenie najważniejszego momentu', 'Realizacja zsynchronizowana z programem')),
    ('0b220c8f-b603-417a-9354-653dd38cefc0'::uuid,
      'Cztery sceniczne fontanny iskier tworzące rozbudowaną oprawę wybranego momentu.',
      'Zestaw czterech fontann iskier pozwala zbudować szerszy i bardziej przestrzenny efekt wizualny. Rozmieszczenie oraz moment uruchomienia ustalamy odpowiednio do miejsca i scenariusza uroczystości.',
      jsonb_build_array('Rozbudowany efekt czterech urządzeń', 'Wyraźna oprawa zdjęć i nagrań', 'Ustawienie dopasowane do przestrzeni')),
    ('ad35c049-7e77-4f7f-8cfd-c33b9eb9d26f'::uuid,
      'Fotolustro w formule dopasowanej do przyjęcia weselnego i jego gości.',
      'Fotolustro tworzy osobną strefę, w której goście mogą swobodnie wykonywać pamiątkowe zdjęcia. Wygląd stanowiska oraz czas działania ustalamy zgodnie z harmonogramem i przestrzenią sali.',
      jsonb_build_array('Pamiątkowe zdjęcia dla gości', 'Atrakcja dostępna niezależnie od parkietu', 'Strefa dopasowana do sali')),
    ('a0d88f1a-6be6-4751-899c-0832b339d21c'::uuid,
      'Czytelne nagłośnienie muzyki i mowy podczas ceremonii ślubnej.',
      'Nagłośnienie ceremonii wspiera odtwarzanie muzyki, wypowiedzi oraz najważniejsze momenty uroczystości. Konfigurację dobieramy do miejsca, liczby uczestników i ustalonego przebiegu ceremonii.',
      jsonb_build_array('Lepsza słyszalność dla gości', 'Obsługa mowy i materiałów muzycznych', 'Konfiguracja do miejsca ceremonii')),
    ('f2dbb30c-9a4b-4e0e-9225-ee3c1490d418'::uuid,
      'Dekoracyjny napis LOVE tworzący rozpoznawalny punkt aranżacji weselnej.',
      'Napis LOVE uzupełnia przestrzeń sali lub wybraną strefę i może stanowić tło do zdjęć. Miejsce ustawienia dobieramy do układu sali oraz pozostałych dekoracji.',
      jsonb_build_array('Wyrazisty element dekoracyjny', 'Tło do pamiątkowych zdjęć', 'Uniwersalne ustawienie w sali')),
    ('c6cbfc04-aebb-40ee-8e97-6ed7e2e40537'::uuid,
      'Dekoracyjny napis MIŁOŚĆ podkreślający charakter uroczystości.',
      'Napis MIŁOŚĆ tworzy czytelny akcent w aranżacji sali weselnej lub strefy fotograficznej. Ustawienie elementu uzgadniamy z uwzględnieniem przestrzeni i pozostałej oprawy.',
      jsonb_build_array('Polski akcent dekoracyjny', 'Dobre tło do zdjęć', 'Spójne uzupełnienie aranżacji')),
    ('33af8c06-3908-4f3e-8a00-6e9bc4f814ac'::uuid,
      'Świetlny napis neonowy jako nowoczesny akcent dekoracyjny wydarzenia.',
      'Napis neonowy przyciąga uwagę i uzupełnia aranżację wybranej strefy. Może zostać wykorzystany jako element tła fotograficznego lub dekoracja widoczna przez całe wydarzenie.',
      jsonb_build_array('Nowoczesny efekt świetlny', 'Wyrazisty punkt aranżacji', 'Atrakcyjne tło fotograficzne')),
    ('775e4640-fc1a-4a9c-a863-a7d0282c224b'::uuid,
      'Pięciogodzinna oprawa muzyczna poprawin dopasowana do luźniejszego charakteru spotkania.',
      'Usługa obejmuje prowadzenie muzycznej części poprawin przez pięć godzin. Repertuar i tempo wydarzenia są dobierane do gości, miejsca oraz ustalonego harmonogramu.',
      jsonb_build_array('Pięć godzin oprawy muzycznej', 'Repertuar dopasowany do gości', 'Płynne prowadzenie poprawin')),
    ('c7cf909d-a5da-43e2-af18-a3e12516d442'::uuid,
      'Muzyka saksofonowa na żywo jako elegancki i energetyczny element wesela.',
      'Saksofonista może uzupełnić wybrane części uroczystości występem na żywo. Repertuar, długość setów i momenty występu ustalamy zgodnie z programem oraz charakterem przyjęcia.',
      jsonb_build_array('Instrument na żywo', 'Wyrazisty punkt programu', 'Repertuar dopasowany do uroczystości')),
    ('6a52779b-2290-4507-aa82-89d21c3d505b'::uuid,
      'Efekt ciężkiego dymu tworzący wrażenie pierwszego tańca ponad chmurami.',
      'Ciężki dym utrzymuje się nisko nad parkietem i buduje wyjątkową oprawę pierwszego tańca. Efekt jest przygotowywany w uzgodnionym momencie, z uwzględnieniem warunków sali i pracy wentylacji.',
      jsonb_build_array('Wyjątkowa oprawa pierwszego tańca', 'Efekt dobrze widoczny na zdjęciach i filmie', 'Realizacja skoordynowana z muzyką')),
    ('480eb215-8285-4a84-bec0-0b9bdf2aded2'::uuid,
      'Dwuosobowa oprawa wydarzenia łącząca uzupełniające się role wykonawców.',
      'Wyjątkowy duet zapewnia wspólną realizację uzgodnionej części programu weselnego. Charakter występu i zakres zaangażowania obu osób są dopasowywane do scenariusza uroczystości.',
      jsonb_build_array('Dwie uzupełniające się role', 'Spójna realizacja programu', 'Formuła dopasowana do uroczystości')),
    ('b0d64727-81eb-4f9f-a61f-66831a74e579'::uuid,
      'Muzyczna oprawa tradycyjnego wyprowadzenia Pary Młodej z domu.',
      'Wyprowadzenie z domu stanowi uroczysty, muzyczny początek weselnego programu. Przebieg i repertuar ustalamy z Parą Młodą, dopasowując oprawę do miejsca oraz rodzinnego charakteru chwili.',
      jsonb_build_array('Uroczyste rozpoczęcie dnia', 'Muzyczna oprawa tradycji', 'Przebieg uzgodniony z Parą Młodą')),
    ('c757f790-20b1-40ef-9f6d-03af6d1ca33b'::uuid,
      'Rozbudowany pakiet DJ-ski z zaawansowaną oprawą techniczną i świetlną.',
      'DJ Premium łączy doświadczenie prowadzącego z rozszerzoną konfiguracją sprzętu i oświetlenia. Program muzyczny oraz charakter prowadzenia są przygotowywane odpowiednio do wydarzenia i oczekiwań organizatora.',
      jsonb_build_array('Rozbudowana oprawa muzyczna i świetlna', 'Doświadczone prowadzenie wydarzenia', 'Konfiguracja dopasowana do programu')),
    ('b7075006-f993-463b-bfc5-204183e58bca'::uuid,
      'Modułowy ekran LED o wymiarach 2 × 3 m do prezentacji obrazu podczas wydarzenia.',
      'Ekran LED 2 × 3 m zapewnia wyraźną powierzchnię do prezentacji materiałów, obrazu z kamer lub identyfikacji wizualnej. Ustawienie i źródło sygnału uzgadniamy z uwzględnieniem sceny oraz widoczności dla uczestników.',
      jsonb_build_array('Czytelny format 2 × 3 m', 'Obsługa prezentacji i obrazu z kamer', 'Wyrazisty element scenografii multimedialnej')),
    ('eae7317d-c459-467d-afe9-17c8074fa47f'::uuid,
      'Dodatkowy mikrofon bezprzewodowy zapewniający swobodę wypowiedzi na sali lub scenie.',
      'Mikrofon bezprzewodowy uzupełnia system nagłośnienia o kolejne niezależne źródło mowy. Sprawdza się podczas prezentacji, paneli, pytań z sali i innych punktów wymagających mobilności.',
      jsonb_build_array('Swoboda poruszania się', 'Dodatkowy kanał dla mówcy', 'Wygodne przekazywanie mikrofonu')),
    ('029c7b93-6e0f-4dd1-a51c-85a71987fa42'::uuid,
      'Podstawowy komplet nagłośnieniowy przeznaczony dla wydarzeń do około 100 osób.',
      'Nagłośnienie Basic zapewnia podstawową konfigurację do odtwarzania muzyki i wzmacniania mowy. Zestaw dobieramy do wydarzenia, układu przestrzeni oraz liczby uczestników nieprzekraczającej około 100 osób.',
      jsonb_build_array('Kompletna podstawowa konfiguracja', 'Obsługa mowy i muzyki', 'Rozwiązanie dla wydarzeń do około 100 osób')),
    ('43af2850-28cf-4e31-9d30-e838f9616fda'::uuid,
      'Profesjonalny system line array dla większych wydarzeń, planowany dla publiczności do około 500 osób.',
      'Nagłośnienie Premium wykorzystuje konfigurację line array zapewniającą równomierne pokrycie większej przestrzeni. Ostateczny układ systemu dobieramy do miejsca, programu i liczby uczestników do około 500 osób.',
      jsonb_build_array('System line array do większych przestrzeni', 'Równomierne pokrycie dźwiękiem', 'Konfiguracja planowana do około 500 osób')),
    ('a84fccca-4278-4d65-877e-940fb0d5d2fc'::uuid,
      'Uniwersalny komplet nagłośnieniowy dla wydarzeń do około 200 osób.',
      'Nagłośnienie Standard zapewnia konfigurację do realizacji mowy, muzyki i typowych punktów programu. System dobieramy do układu sali oraz wydarzeń liczących do około 200 uczestników.',
      jsonb_build_array('Uniwersalna obsługa mowy i muzyki', 'Zestaw dla wydarzeń do około 200 osób', 'Konfiguracja dopasowana do sali')),
    ('f545e8e5-17fe-402b-96ee-8c5aefd064aa'::uuid,
      'Podstawowe oświetlenie parkietu z wykorzystaniem czterech reflektorów LED.',
      'Pakiet Basic buduje czytelną oprawę świetlną strefy tanecznej przy pomocy czterech reflektorów LED. Kolory i ustawienie urządzeń dobieramy do sali oraz charakteru wydarzenia.',
      jsonb_build_array('Cztery reflektory LED', 'Kolorystyczna oprawa parkietu', 'Podstawowa kompletna konfiguracja')),
    ('160dd9bd-b28a-41e8-adc0-ccba526483a3'::uuid,
      'Rozbudowane oświetlenie parkietu z ośmioma reflektorami LED i ruchomymi głowami.',
      'Pakiet Premium zapewnia dynamiczną oprawę strefy tanecznej, łącząc osiem reflektorów LED z urządzeniami ruchomymi. Program światła może reagować na muzykę i zmieniający się przebieg imprezy.',
      jsonb_build_array('Osiem reflektorów LED', 'Dynamiczne efekty ruchomych głów', 'Rozbudowana oprawa parkietu')),
    ('7656fa5b-d5cf-43bd-b546-2e8beb3804a5'::uuid,
      'Projektor Full HD z ekranem o szerokości 3 m do prezentacji materiałów podczas wydarzenia.',
      'Zestaw projektora i ekranu umożliwia wyświetlanie prezentacji, filmów oraz materiałów informacyjnych. Miejsce ustawienia i warunki projekcji weryfikujemy z uwzględnieniem widoczności oraz oświetlenia sali.',
      jsonb_build_array('Obraz Full HD', 'Ekran o szerokości 3 m', 'Kompletny zestaw do prezentacji')),
    ('989a68ac-0428-4c73-8e63-315ba1776d49'::uuid,
      'Krótki materiał wideo pokazujący najważniejsze momenty i atmosferę wydarzenia.',
      'Rolka video to dynamiczna forma podsumowania realizacji przeznaczona do wygodnego publikowania w kanałach internetowych. Zakres nagrań, długość i sposób montażu ustalamy przed wydarzeniem.',
      jsonb_build_array('Dynamiczne podsumowanie wydarzenia', 'Format odpowiedni do publikacji online', 'Zakres materiału ustalony przed realizacją'))
)
UPDATE public.offer_products AS product
SET
  offer_short_description = CASE
    WHEN NULLIF(BTRIM(product.offer_short_description), '') IS NULL
      THEN product_copy.short_description
    ELSE product.offer_short_description
  END,
  offer_description = CASE
    WHEN NULLIF(BTRIM(product.offer_description), '') IS NULL
      THEN product_copy.full_description
    ELSE product.offer_description
  END,
  offer_benefits = CASE
    WHEN COALESCE(product.offer_benefits, '[]'::jsonb) = '[]'::jsonb
      THEN product_copy.benefits
    ELSE product.offer_benefits
  END
FROM product_copy
WHERE product.id = product_copy.id
  AND product.is_active = true
  AND (
    NULLIF(BTRIM(product.offer_short_description), '') IS NULL
    OR NULLIF(BTRIM(product.offer_description), '') IS NULL
    OR COALESCE(product.offer_benefits, '[]'::jsonb) = '[]'::jsonb
  );
