import assert from 'node:assert/strict';
export async function scenarios(db) {
 const q=async(sql,params=[]) => (await db.query(sql,params)).rows;
 const scalar=async(sql,params=[])=>Object.values((await q(sql,params))[0])[0];
 const id=async()=>scalar('select gen_random_uuid()');
 const owner=await id(), outsider=await id(), inquiry=await id(), calc=await id(), offer=await id(), second=await id();
 await q("insert into employees(id,role,permissions) values($1,'admin',array['admin']),($2,'employee',array['inquiries_view'])",[owner,outsider]);
 await q("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
 await q("insert into tasks(id,title,is_inquiry,inquiry_owner_id,inquiry_stage,inquiry_details) values($1,'Test',true,$2,'qualified','{}')",[inquiry,owner]);
 await q("insert into event_calculations(id,inquiry_id,name) values($1,$2,'A')",[calc,inquiry]);
 await q("insert into event_calculation_items(calculation_id,name,quantity,unit_price,position) values($1,'Światło',2,100,1)",[calc]);
 await q("insert into offers(id,inquiry_id,status,offer_number,title,source_calculation_id) values($1,$2,'draft','OF/A','A',$3)",[offer,inquiry,calc]);
 await q("insert into offer_items(offer_id,name,quantity,unit_price,display_order) values($1,'Światło',2,100,1)",[offer]);
 const snapshot=await scalar('select calculation_snapshot from offers where id=$1',[offer]);
 await q('update event_calculation_items set unit_price=300 where calculation_id=$1',[calc]);
 assert.deepEqual(await scalar('select calculation_snapshot from offers where id=$1',[offer]),snapshot);
 const copy=await scalar('select duplicate_sales_offer($1,$2)',[offer,second]);
 assert.equal(copy,second);assert.equal(await scalar('select duplicate_sales_offer($1,$2)',[offer,second]),second);
 assert.deepEqual(await scalar('select calculation_snapshot from offers where id=$1',[second]),snapshot);
 assert.equal(await scalar('select count(*)::int from offer_items where offer_id=$1',[second]),1);
 const calcCopy=await scalar('select duplicate_sales_calculation($1,$2)',[calc,await id()]);
 assert.equal(calcCopy.items[0].unit_price,300);assert.equal(calcCopy.calculation.is_accepted,false);
 const packageId=await id(); await q("insert into offer_packages(id,offer_id,name,display_order) values($1,$2,'Pakiet',1)",[packageId,second]);
 await q('insert into offer_package_items(package_id,offer_item_id,quantity,display_order) select $1,id,2,1 from offer_items where offer_id=$2',[packageId,second]);
 const packageCopy=await scalar('select duplicate_sales_offer($1,$2)',[second,await id()]);
 assert.equal(await scalar('select count(*)::int from offer_package_items i join offer_packages p on p.id=i.package_id where p.offer_id=$1',[packageCopy]),1);
 assert.notEqual(await scalar('select id from offer_packages where offer_id=$1',[packageCopy]),packageId);
 assert.equal(await scalar('select i.offer_id from offer_items i join offer_package_items pi on pi.offer_item_id=i.id join offer_packages p on p.id=pi.package_id where p.offer_id=$1',[packageCopy]),packageCopy);
 await q('select select_inquiry_calculation($1,null)',[calc]);
 await assert.rejects(q('select select_inquiry_calculation($1,null)',[calcCopy.calculation.id]),/Odśwież/);
 console.log('PASS independent snapshots, atomic/idempotent offer and calculation copies');
 await q("update event_calculations set generated_pdf_path='old.pdf',generated_pdf_revision=content_revision where id=$1",[calc]);
 await q('update event_calculation_items set quantity=3 where calculation_id=$1',[calc]);
 assert.equal(await scalar('select generated_pdf_path from event_calculations where id=$1',[calc]),null);
 const revision=await scalar('select content_revision from event_calculations where id=$1',[calc]);
 await q("select set_config('request.jwt.claim.role','service_role',false)");
 await assert.rejects(q("select publish_calculation_pdf($1,$2,'stale.pdf')",[calc,revision-1]),/zmieniła/);
 assert.equal(await scalar("select count(*)::int from sales_document_files where storage_path='stale.pdf'"),0);
 await q("select publish_calculation_pdf($1,$2,'current.pdf')",[calc,revision]);
 assert.equal(await scalar('select generated_pdf_revision from event_calculations where id=$1',[calc]),revision);
 await q("select set_config('request.jwt.claim.role','authenticated',false)");
 console.log('PASS persisted price/content changes invalidate calculation PDF');
 const brief=await scalar('select save_inquiry_brief($1,1,$2)',[inquiry,JSON.stringify({questions:[{id:'q1',question:'Ile osób?',answer:'120',status:'answered',source:'Telefon'}],preliminary_budget_min:100,preliminary_budget_max:200})]);
 assert.equal(brief.brief_revision,2);assert.equal(brief.estimated_value,150);
 await assert.rejects(q('select save_inquiry_brief($1,1,$2)',[inquiry,'{}']),/Odśwież/);
 await assert.rejects(q('select save_inquiry_analysis($1,1,$2)',[inquiry,'{}']),/zmienił/);
 await q('select save_inquiry_analysis($1,2,$2)',[inquiry,'{"summary":"Test"}']);
 console.log('PASS brief and analysis reject stale revisions and keep Q/A history');
 await q("select set_config('request.jwt.claim.sub',$1,false)",[outsider]);
 await assert.rejects(q('select duplicate_sales_offer($1,$2)',[offer,await id()]),/uprawnień/);
 await assert.rejects(q('select save_inquiry_brief($1,2,$2)',[inquiry,'{}']),/uprawnień/);
 await q("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
 await q("select accept_inquiry_offer($1,'Telefon: klient potwierdził',null,null)",[offer]);
 await assert.rejects(q("select accept_inquiry_offer($1,'Drugi klient',null,null)",[second]),/Odśwież/);
 assert.equal(await scalar('select accepted_offer_id from tasks where id=$1',[inquiry]),offer);
 await assert.rejects(q("update offers set status='sent' where id=$1",[offer]),/wariant/);
 await assert.rejects(q("update offer_items set quantity=9 where offer_id=$1",[offer]),/zakresu/);
 await q("select set_config('request.jwt.claim.role','service_role',false)");
 await q("select record_sales_delivery('offer',$1,'test-delivery','offer.pdf','test@example.invalid')",[offer]);
 assert.equal(await scalar('select status from offers where id=$1',[offer]),'accepted');
 assert.equal(await scalar('select inquiry_stage from tasks where id=$1',[inquiry]),'won');
 await q("select record_sales_delivery('offer',$1,'test-delivery','offer.pdf','test@example.invalid')",[offer]);
 assert.equal(await scalar("select count(*)::int from inquiry_activity where delivery_key='test-delivery'"),1);
 await q("select set_config('request.jwt.claim.role','authenticated',false)");
 console.log('PASS viewer denied, stale acceptance rejected, accepted content locked, resend preserves won');
 const event=await scalar("select prepare_inquiry_realization($1,'Event',now(),null,null)",[inquiry]);
 assert.equal(await scalar("select prepare_inquiry_realization($1,'Event',now(),null,null)",[inquiry]),event);
 assert.equal(await scalar('select count(*)::int from tasks where inquiry_id=$1',[inquiry]),1);
 assert.equal(Number(await scalar('select budget from events where id=$1',[event])),200);
 assert.equal(await scalar('select count(*)::int from event_equipment where event_id=$1',[event]),1);
 console.log('PASS idempotent accepted handoff with frozen budget, planned resources and task');
 const draftInquiry=await id();await q("insert into tasks(id,title,is_inquiry,inquiry_owner_id,inquiry_stage) values($1,'Draft',true,$2,'qualified')",[draftInquiry,owner]);
 await scalar("select convert_inquiry_to_event($1,'Draft',now(),null,null)",[draftInquiry]);assert.equal(await scalar('select inquiry_stage from tasks where id=$1',[draftInquiry]),'qualified');
 await q("select archive_inquiry($1,'Test')",[draftInquiry]);assert.ok(await scalar('select archived_at from tasks where id=$1',[draftInquiry]));
 await assert.rejects(q('delete from tasks where id=$1',[draftInquiry]),/Archiwizuj/);
 console.log('PASS draft event keeps sale open and archival preserves source');
 // Install source triggers from the existing routing migration fixture explicitly.
 await db.exec(`CREATE FUNCTION create_inquiry_from_contact_message() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN PERFORM ensure_intake_inquiry('contact_form',NEW.id); RETURN NEW; END $$;
 CREATE TRIGGER source_message AFTER INSERT ON contact_messages FOR EACH ROW EXECUTE FUNCTION create_inquiry_from_contact_message();
 CREATE TRIGGER source_submission AFTER INSERT ON contact_form_submissions FOR EACH ROW EXECUTE FUNCTION process_contact_form_submission();`);
 const sub=await id();await q("insert into contact_form_submissions(id,name,email,message,city_interest,event_type) values($1,'Test','test@example.invalid','Event','Gdańsk','Konferencja')",[sub]);
 const source=await scalar("select (metadata->>'message_id')::uuid from contact_form_submissions where id=$1",[sub]);
 const sourceInquiry=await scalar("select ensure_intake_inquiry('contact_form',$1)",[source]);
 assert.equal(await scalar("select ensure_intake_inquiry('contact_form',$1)",[source]),sourceInquiry);
 assert.equal(await scalar("select inquiry_details->>'location_text' from tasks where id=$1",[sourceInquiry]),'Gdańsk');
 const oldSource=await id();await q("insert into contact_messages(id,name,message) values($1,'Old','Old')",[oldSource]);
 await q("insert into inquiry_intake_reviews(source_kind,source_id) values('contact_form',$1)",[oldSource]);
 await q("select resolve_inquiry_intake_review('contact_form',$1,'link','Obsłużone wcześniej',$2)",[oldSource,inquiry]);
 assert.equal(await scalar("select ensure_intake_inquiry('contact_form',$1)",[oldSource]),inquiry);
 console.log('PASS transactional form intake, structured city and stable retry/link resolution');
}
